// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: espDisplayUi

#include "ui.h"

lv_obj_t * ui_ListaRedes = NULL;
lv_obj_t * ui_PanelWifiList = NULL;
lv_obj_t * ui_LabelStatus = NULL;
lv_obj_t * ui_buttonScan = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_PanelPassword = NULL;
lv_obj_t * ui_TextAreaPassword = NULL;
lv_obj_t * ui_LabelSSDSelection = NULL;
lv_obj_t * ui_LabelSenha = NULL;
lv_obj_t * ui_ButtonConect = NULL;
lv_obj_t * ui_labelBotaoConecta2 = NULL;
lv_obj_t * ui_ButtonCancel = NULL;
lv_obj_t * ui_labelBotaoConecta4 = NULL;
lv_obj_t * ui_Spinner6 = NULL;
lv_obj_t * ui_KeyboardWifiCaseira = NULL;
// event funtions
void ui_event_ListaRedes(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        _ui_flag_modify(ui_Spinner6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_buttonScan(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ListaRedes, LV_SCR_LOAD_ANIM_OVER_RIGHT, 500, 0, &ui_ListaRedes_screen_init);
    }
}

void ui_event_TextAreaPassword(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_KeyboardWifiCaseira, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_KeyboardWifiCaseira,  ui_TextAreaPassword);
    }
}

void ui_event_ButtonConect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Spinner6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_screen_change(&ui_ParametrosEspRemoto, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 1000, &ui_ParametrosEspRemoto_screen_init);
    }
}

void ui_event_ButtonCancel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Spinner6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_screen_change(&ui_ParametrosEspRemoto, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 8000, &ui_ParametrosEspRemoto_screen_init);
    }
}

void ui_event_KeyboardWifiCaseira(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_KeyboardWifiCaseira, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

void ui_ListaRedes_screen_init(void)
{
    ui_ListaRedes = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ListaRedes, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);    /// Flags
    lv_obj_set_scrollbar_mode(ui_ListaRedes, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_ListaRedes, LV_DIR_TOP);
    lv_obj_set_scroll_snap_x(ui_ListaRedes, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_style_bg_color(ui_ListaRedes, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ListaRedes, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelWifiList = lv_obj_create(ui_ListaRedes);
    lv_obj_set_width(ui_PanelWifiList, 308);
    lv_obj_set_height(ui_PanelWifiList, 194);
    lv_obj_set_x(ui_PanelWifiList, -1);
    lv_obj_set_y(ui_PanelWifiList, 18);
    lv_obj_set_align(ui_PanelWifiList, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_PanelWifiList, lv_color_hex(0xF3F3FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelWifiList, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelStatus = lv_label_create(ui_ListaRedes);
    lv_obj_set_width(ui_LabelStatus, 193);
    lv_obj_set_height(ui_LabelStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelStatus, 0);
    lv_obj_set_y(ui_LabelStatus, -100);
    lv_obj_set_align(ui_LabelStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelStatus, "Procurando redes..............");
    lv_obj_set_style_text_align(ui_LabelStatus, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelStatus, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonScan = lv_btn_create(ui_ListaRedes);
    lv_obj_set_width(ui_buttonScan, 25);
    lv_obj_set_height(ui_buttonScan, 25);
    lv_obj_set_x(ui_buttonScan, 131);
    lv_obj_set_y(ui_buttonScan, -104);
    lv_obj_set_align(ui_buttonScan, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonScan, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_buttonScan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_buttonScan, lv_color_hex(0x1C13EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonScan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_buttonScan, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_buttonScan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_buttonScan, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_buttonScan, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_buttonScan);
    lv_img_set_src(ui_Image3, &ui_img_atualizar_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_Image3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Image3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPassword = lv_obj_create(ui_ListaRedes);
    lv_obj_set_width(ui_PanelPassword, lv_pct(85));
    lv_obj_set_height(ui_PanelPassword, lv_pct(60));
    lv_obj_set_x(ui_PanelPassword, 0);
    lv_obj_set_y(ui_PanelPassword, 12);
    lv_obj_set_align(ui_PanelPassword, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelPassword, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_PanelPassword, lv_color_hex(0xE0DFFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPassword, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaPassword = lv_textarea_create(ui_PanelPassword);
    lv_obj_set_width(ui_TextAreaPassword, 205);
    lv_obj_set_height(ui_TextAreaPassword, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_TextAreaPassword, -28);
    lv_obj_set_y(ui_TextAreaPassword, -14);
    lv_obj_set_align(ui_TextAreaPassword, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextAreaPassword, 100);
    lv_textarea_set_placeholder_text(ui_TextAreaPassword, "Senha");
    lv_textarea_set_one_line(ui_TextAreaPassword, true);
    lv_textarea_set_password_mode(ui_TextAreaPassword, true);

    ui_LabelSSDSelection = lv_label_create(ui_PanelPassword);
    lv_obj_set_width(ui_LabelSSDSelection, 244);
    lv_obj_set_height(ui_LabelSSDSelection, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSSDSelection, -8);
    lv_obj_set_y(ui_LabelSSDSelection, -63);
    lv_obj_set_align(ui_LabelSSDSelection, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSSDSelection, "Nome da Rede");

    ui_LabelSenha = lv_label_create(ui_PanelPassword);
    lv_obj_set_width(ui_LabelSenha, 232);
    lv_obj_set_height(ui_LabelSenha, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSenha, -12);
    lv_obj_set_y(ui_LabelSenha, -44);
    lv_obj_set_align(ui_LabelSenha, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSenha, "Senha");
    lv_obj_set_style_text_align(ui_LabelSenha, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonConect = lv_btn_create(ui_PanelPassword);
    lv_obj_set_width(ui_ButtonConect, 100);
    lv_obj_set_height(ui_ButtonConect, 32);
    lv_obj_set_x(ui_ButtonConect, 69);
    lv_obj_set_y(ui_ButtonConect, 39);
    lv_obj_set_align(ui_ButtonConect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonConect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonConect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonConect, lv_color_hex(0x0FD93F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonConect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonConect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonConect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_ButtonConect, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_ButtonConect, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ButtonConect, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ButtonConect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ButtonConect, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelBotaoConecta2 = lv_label_create(ui_ButtonConect);
    lv_obj_set_width(ui_labelBotaoConecta2, 82);
    lv_obj_set_height(ui_labelBotaoConecta2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelBotaoConecta2, 1);
    lv_obj_set_y(ui_labelBotaoConecta2, 0);
    lv_obj_set_align(ui_labelBotaoConecta2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelBotaoConecta2, "Conectar");

    ui_ButtonCancel = lv_btn_create(ui_PanelPassword);
    lv_obj_set_width(ui_ButtonCancel, 100);
    lv_obj_set_height(ui_ButtonCancel, 32);
    lv_obj_set_x(ui_ButtonCancel, -77);
    lv_obj_set_y(ui_ButtonCancel, 37);
    lv_obj_set_align(ui_ButtonCancel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonCancel, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonCancel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonCancel, lv_color_hex(0xEF0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonCancel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonCancel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonCancel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_ButtonCancel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_ButtonCancel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ButtonCancel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ButtonCancel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ButtonCancel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelBotaoConecta4 = lv_label_create(ui_ButtonCancel);
    lv_obj_set_width(ui_labelBotaoConecta4, 82);
    lv_obj_set_height(ui_labelBotaoConecta4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelBotaoConecta4, 1);
    lv_obj_set_y(ui_labelBotaoConecta4, 0);
    lv_obj_set_align(ui_labelBotaoConecta4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelBotaoConecta4, "Cancelar");

    ui_Spinner6 = lv_spinner_create(ui_PanelPassword, 1000, 90);
    lv_obj_set_width(ui_Spinner6, 33);
    lv_obj_set_height(ui_Spinner6, 26);
    lv_obj_set_x(ui_Spinner6, 115);
    lv_obj_set_y(ui_Spinner6, -42);
    lv_obj_set_align(ui_Spinner6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner6, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Spinner6, lv_color_hex(0xE0DFFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Spinner6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Spinner6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Spinner6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Spinner6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner6, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Spinner6, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner6, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner6, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_KeyboardWifiCaseira = lv_keyboard_create(ui_ListaRedes);
    lv_obj_set_width(ui_KeyboardWifiCaseira, 316);
    lv_obj_set_height(ui_KeyboardWifiCaseira, 100);
    lv_obj_set_x(ui_KeyboardWifiCaseira, 1);
    lv_obj_set_y(ui_KeyboardWifiCaseira, 70);
    lv_obj_set_align(ui_KeyboardWifiCaseira, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KeyboardWifiCaseira, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_KeyboardWifiCaseira, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_KeyboardWifiCaseira, lv_color_hex(0x223E50), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KeyboardWifiCaseira, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_KeyboardWifiCaseira, 10, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_KeyboardWifiCaseira, lv_color_hex(0x366381), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KeyboardWifiCaseira, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_KeyboardWifiCaseira, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_KeyboardWifiCaseira, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_KeyboardWifiCaseira, lv_color_hex(0xD5EFFF), LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_KeyboardWifiCaseira, 255, LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_KeyboardWifiCaseira, lv_color_hex(0x224359), LV_PART_ITEMS | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_KeyboardWifiCaseira, 255, LV_PART_ITEMS | LV_STATE_PRESSED);
    lv_obj_set_style_outline_color(ui_KeyboardWifiCaseira, lv_color_hex(0x009FC7), LV_PART_ITEMS | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_KeyboardWifiCaseira, 255, LV_PART_ITEMS | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(ui_KeyboardWifiCaseira, 3, LV_PART_ITEMS | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_KeyboardWifiCaseira, 0, LV_PART_ITEMS | LV_STATE_PRESSED);
    lv_obj_set_style_text_color(ui_KeyboardWifiCaseira, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_KeyboardWifiCaseira, 255, LV_PART_ITEMS | LV_STATE_PRESSED);

    lv_obj_add_event_cb(ui_buttonScan, ui_event_buttonScan, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaPassword, ui_event_TextAreaPassword, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonConect, ui_event_ButtonConect, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonCancel, ui_event_ButtonCancel, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_KeyboardWifiCaseira, ui_TextAreaPassword);
    lv_obj_add_event_cb(ui_KeyboardWifiCaseira, ui_event_KeyboardWifiCaseira, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ListaRedes, ui_event_ListaRedes, LV_EVENT_ALL, NULL);

}

void ui_ListaRedes_screen_destroy(void)
{
    if(ui_ListaRedes) lv_obj_del(ui_ListaRedes);

    // NULL screen variables
    ui_ListaRedes = NULL;
    ui_PanelWifiList = NULL;
    ui_LabelStatus = NULL;
    ui_buttonScan = NULL;
    ui_Image3 = NULL;
    ui_PanelPassword = NULL;
    ui_TextAreaPassword = NULL;
    ui_LabelSSDSelection = NULL;
    ui_LabelSenha = NULL;
    ui_ButtonConect = NULL;
    ui_labelBotaoConecta2 = NULL;
    ui_ButtonCancel = NULL;
    ui_labelBotaoConecta4 = NULL;
    ui_Spinner6 = NULL;
    ui_KeyboardWifiCaseira = NULL;

}
