// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: espDisplayUi

#ifndef UI_LISTAREDES_H
#define UI_LISTAREDES_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ListaRedes
extern void ui_ListaRedes_screen_init(void);
extern void ui_ListaRedes_screen_destroy(void);
extern void ui_event_ListaRedes(lv_event_t * e);
extern lv_obj_t * ui_ListaRedes;
extern lv_obj_t * ui_PanelWifiList;
extern lv_obj_t * ui_LabelStatus;
extern void ui_event_buttonScan(lv_event_t * e);
extern lv_obj_t * ui_buttonScan;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_PanelPassword;
extern void ui_event_TextAreaPassword(lv_event_t * e);
extern lv_obj_t * ui_TextAreaPassword;
extern lv_obj_t * ui_LabelSSDSelection;
extern lv_obj_t * ui_LabelSenha;
extern void ui_event_ButtonConect(lv_event_t * e);
extern lv_obj_t * ui_ButtonConect;
extern lv_obj_t * ui_labelBotaoConecta2;
extern void ui_event_ButtonCancel(lv_event_t * e);
extern lv_obj_t * ui_ButtonCancel;
extern lv_obj_t * ui_labelBotaoConecta4;
extern lv_obj_t * ui_Spinner6;
extern void ui_event_KeyboardWifiCaseira(lv_event_t * e);
extern lv_obj_t * ui_KeyboardWifiCaseira;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

