// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: espDisplayUi

#include "ui.h"

lv_obj_t * ui_ParametrosExperimento = NULL;
lv_obj_t * ui_painelIputs2 = NULL;
lv_obj_t * ui_inputObserKe = NULL;
lv_obj_t * ui_inputRegulaK = NULL;
lv_obj_t * ui_inputNEstados = NULL;
lv_obj_t * ui_inputNEntradas = NULL;
lv_obj_t * ui_inputReferencia = NULL;
lv_obj_t * ui_tituloTelaParametrosBroker2 = NULL;
lv_obj_t * ui_botaoEnviaDados = NULL;
lv_obj_t * ui_labelBotaoEnviaParametro = NULL;
lv_obj_t * ui_Spinner4 = NULL;
lv_obj_t * ui_botaoReseta5 = NULL;
lv_obj_t * ui_Label41 = NULL;
lv_obj_t * ui_KeyboardExperimento = NULL;
lv_obj_t * ui_botaoVolta3 = NULL;
lv_obj_t * ui_Label6 = NULL;
// event funtions
void ui_event_ParametrosExperimento(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        _ui_flag_modify(ui_Spinner4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_inputObserKe(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_KeyboardExperimento, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_KeyboardExperimento,  ui_inputObserKe);
    }
}

void ui_event_inputRegulaK(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_KeyboardExperimento, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_KeyboardExperimento,  ui_inputRegulaK);
        _ui_basic_set_property(ui_painelIputs2, _UI_BASIC_PROPERTY_POSITION_Y,  -75);
        _ui_basic_set_property(ui_tituloTelaParametrosBroker2, _UI_BASIC_PROPERTY_POSITION_Y,  -150);
        _ui_basic_set_property(ui_botaoReseta5, _UI_BASIC_PROPERTY_POSITION_Y,  -150);
        _ui_basic_set_property(ui_botaoVolta3, _UI_BASIC_PROPERTY_POSITION_Y,  -150);
    }
}

void ui_event_inputNEstados(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_KeyboardExperimento, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_KeyboardExperimento,  ui_inputNEstados);
        _ui_basic_set_property(ui_painelIputs2, _UI_BASIC_PROPERTY_POSITION_Y,  -75);
        _ui_basic_set_property(ui_tituloTelaParametrosBroker2, _UI_BASIC_PROPERTY_POSITION_Y,  -150);
        _ui_basic_set_property(ui_botaoReseta5, _UI_BASIC_PROPERTY_POSITION_Y,  -150);
        _ui_basic_set_property(ui_botaoVolta3, _UI_BASIC_PROPERTY_POSITION_Y,  -150);
    }
}

void ui_event_inputNEntradas(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_KeyboardExperimento, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_KeyboardExperimento,  ui_inputNEntradas);
        _ui_basic_set_property(ui_tituloTelaParametrosBroker2, _UI_BASIC_PROPERTY_POSITION_Y,  -150);
        _ui_basic_set_property(ui_painelIputs2, _UI_BASIC_PROPERTY_POSITION_Y,  -75);
        _ui_basic_set_property(ui_botaoReseta5, _UI_BASIC_PROPERTY_POSITION_Y,  -150);
        _ui_basic_set_property(ui_botaoVolta3, _UI_BASIC_PROPERTY_POSITION_Y,  -150);
    }
}

void ui_event_inputReferencia(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_KeyboardExperimento, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_KeyboardExperimento,  ui_inputReferencia);
        _ui_basic_set_property(ui_painelIputs2, _UI_BASIC_PROPERTY_POSITION_Y,  -75);
        _ui_basic_set_property(ui_tituloTelaParametrosBroker2, _UI_BASIC_PROPERTY_POSITION_Y,  -150);
        _ui_basic_set_property(ui_botaoReseta5, _UI_BASIC_PROPERTY_POSITION_Y,  -150);
        _ui_basic_set_property(ui_botaoVolta3, _UI_BASIC_PROPERTY_POSITION_Y,  -150);
    }
}

void ui_event_botaoEnviaDados(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Spinner4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_screen_change(&ui_Sucesso, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui_Sucesso_screen_init);
    }
}

void ui_event_KeyboardExperimento(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_KeyboardExperimento, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_basic_set_property(ui_painelIputs2, _UI_BASIC_PROPERTY_POSITION_Y,  -8);
        _ui_basic_set_property(ui_tituloTelaParametrosBroker2, _UI_BASIC_PROPERTY_POSITION_Y,  -100);
        _ui_basic_set_property(ui_botaoReseta5, _UI_BASIC_PROPERTY_POSITION_Y,  -104);
        _ui_basic_set_property(ui_botaoVolta3, _UI_BASIC_PROPERTY_POSITION_Y,  -104);
    }
}

void ui_event_botaoVolta3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ParametrosEspRemoto, LV_SCR_LOAD_ANIM_OVER_RIGHT, 500, 0, &ui_ParametrosEspRemoto_screen_init);
    }
}

// build funtions

void ui_ParametrosExperimento_screen_init(void)
{
    ui_ParametrosExperimento = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ParametrosExperimento,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_ParametrosExperimento, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_snap_x(ui_ParametrosExperimento, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_style_bg_color(ui_ParametrosExperimento, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ParametrosExperimento, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_painelIputs2 = lv_obj_create(ui_ParametrosExperimento);
    lv_obj_set_width(ui_painelIputs2, 300);
    lv_obj_set_height(ui_painelIputs2, 137);
    lv_obj_set_x(ui_painelIputs2, 0);
    lv_obj_set_y(ui_painelIputs2, -8);
    lv_obj_set_align(ui_painelIputs2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_painelIputs2, LV_OBJ_FLAG_SCROLL_WITH_ARROW | LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_clear_flag(ui_painelIputs2, LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scrollbar_mode(ui_painelIputs2, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_painelIputs2, LV_DIR_VER);
    lv_obj_set_scroll_snap_x(ui_painelIputs2, LV_SCROLL_SNAP_END);
    lv_obj_set_style_bg_color(ui_painelIputs2, lv_color_hex(0xE0DFFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_painelIputs2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_inputObserKe = lv_textarea_create(ui_painelIputs2);
    lv_obj_set_width(ui_inputObserKe, 176);
    lv_obj_set_height(ui_inputObserKe, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_inputObserKe, -51);
    lv_obj_set_y(ui_inputObserKe, -41);
    lv_obj_set_align(ui_inputObserKe, LV_ALIGN_CENTER);
    if("123456789," == "") lv_textarea_set_accepted_chars(ui_inputObserKe, NULL);
    else lv_textarea_set_accepted_chars(ui_inputObserKe, "123456789,");
    lv_textarea_set_max_length(ui_inputObserKe, 6);
    lv_textarea_set_placeholder_text(ui_inputObserKe, "Observador Ke");
    lv_textarea_set_one_line(ui_inputObserKe, true);

    ui_inputRegulaK = lv_textarea_create(ui_painelIputs2);
    lv_obj_set_width(ui_inputRegulaK, 181);
    lv_obj_set_height(ui_inputRegulaK, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_inputRegulaK, -50);
    lv_obj_set_y(ui_inputRegulaK, 6);
    lv_obj_set_align(ui_inputRegulaK, LV_ALIGN_CENTER);
    if("123456789," == "") lv_textarea_set_accepted_chars(ui_inputRegulaK, NULL);
    else lv_textarea_set_accepted_chars(ui_inputRegulaK, "123456789,");
    lv_textarea_set_max_length(ui_inputRegulaK, 6);
    lv_textarea_set_placeholder_text(ui_inputRegulaK, "Regulador K");
    lv_textarea_set_one_line(ui_inputRegulaK, true);

    ui_inputNEstados = lv_textarea_create(ui_painelIputs2);
    lv_obj_set_width(ui_inputNEstados, 181);
    lv_obj_set_height(ui_inputNEstados, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_inputNEstados, -50);
    lv_obj_set_y(ui_inputNEstados, 54);
    lv_obj_set_align(ui_inputNEstados, LV_ALIGN_CENTER);
    if("123456789," == "") lv_textarea_set_accepted_chars(ui_inputNEstados, NULL);
    else lv_textarea_set_accepted_chars(ui_inputNEstados, "123456789,");
    lv_textarea_set_max_length(ui_inputNEstados, 6);
    lv_textarea_set_placeholder_text(ui_inputNEstados, "N° de estados Nx");
    lv_textarea_set_one_line(ui_inputNEstados, true);

    ui_inputNEntradas = lv_textarea_create(ui_painelIputs2);
    lv_obj_set_width(ui_inputNEntradas, 181);
    lv_obj_set_height(ui_inputNEntradas, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_inputNEntradas, -51);
    lv_obj_set_y(ui_inputNEntradas, 101);
    lv_obj_set_align(ui_inputNEntradas, LV_ALIGN_CENTER);
    if("123456789," == "") lv_textarea_set_accepted_chars(ui_inputNEntradas, NULL);
    else lv_textarea_set_accepted_chars(ui_inputNEntradas, "123456789,");
    lv_textarea_set_max_length(ui_inputNEntradas, 6);
    lv_textarea_set_placeholder_text(ui_inputNEntradas, "N° de entradas Nu");
    lv_textarea_set_one_line(ui_inputNEntradas, true);

    ui_inputReferencia = lv_textarea_create(ui_painelIputs2);
    lv_obj_set_width(ui_inputReferencia, 181);
    lv_obj_set_height(ui_inputReferencia, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_inputReferencia, -47);
    lv_obj_set_y(ui_inputReferencia, 146);
    lv_obj_set_align(ui_inputReferencia, LV_ALIGN_CENTER);
    if("123456789," == "") lv_textarea_set_accepted_chars(ui_inputReferencia, NULL);
    else lv_textarea_set_accepted_chars(ui_inputReferencia, "123456789,");
    lv_textarea_set_max_length(ui_inputReferencia, 6);
    lv_textarea_set_placeholder_text(ui_inputReferencia, "Referencia");

    ui_tituloTelaParametrosBroker2 = lv_label_create(ui_ParametrosExperimento);
    lv_obj_set_width(ui_tituloTelaParametrosBroker2, 230);
    lv_obj_set_height(ui_tituloTelaParametrosBroker2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tituloTelaParametrosBroker2, 3);
    lv_obj_set_y(ui_tituloTelaParametrosBroker2, -100);
    lv_obj_set_align(ui_tituloTelaParametrosBroker2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tituloTelaParametrosBroker2,
                      "Insira os dados abaixo para enviar a \nbancada os dados experimentais");
    lv_obj_set_style_text_align(ui_tituloTelaParametrosBroker2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tituloTelaParametrosBroker2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_botaoEnviaDados = lv_btn_create(ui_ParametrosExperimento);
    lv_obj_set_width(ui_botaoEnviaDados, 174);
    lv_obj_set_height(ui_botaoEnviaDados, 32);
    lv_obj_set_x(ui_botaoEnviaDados, 61);
    lv_obj_set_y(ui_botaoEnviaDados, 90);
    lv_obj_set_align(ui_botaoEnviaDados, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_botaoEnviaDados, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_botaoEnviaDados, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_botaoEnviaDados, lv_color_hex(0x0FD93F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_botaoEnviaDados, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_botaoEnviaDados, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_botaoEnviaDados, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_botaoEnviaDados, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_botaoEnviaDados, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_botaoEnviaDados, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_botaoEnviaDados, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_botaoEnviaDados, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelBotaoEnviaParametro = lv_label_create(ui_botaoEnviaDados);
    lv_obj_set_width(ui_labelBotaoEnviaParametro, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelBotaoEnviaParametro, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelBotaoEnviaParametro, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelBotaoEnviaParametro, "Enviar dados");

    ui_Spinner4 = lv_spinner_create(ui_ParametrosExperimento, 1000, 90);
    lv_obj_set_width(ui_Spinner4, 33);
    lv_obj_set_height(ui_Spinner4, 26);
    lv_obj_set_x(ui_Spinner4, -126);
    lv_obj_set_y(ui_Spinner4, 92);
    lv_obj_set_align(ui_Spinner4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner4, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Spinner4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Spinner4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Spinner4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Spinner4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Spinner4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Spinner4, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner4, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_botaoReseta5 = lv_btn_create(ui_ParametrosExperimento);
    lv_obj_set_width(ui_botaoReseta5, 25);
    lv_obj_set_height(ui_botaoReseta5, 25);
    lv_obj_set_x(ui_botaoReseta5, 145);
    lv_obj_set_y(ui_botaoReseta5, -106);
    lv_obj_set_align(ui_botaoReseta5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_botaoReseta5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_botaoReseta5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_botaoReseta5, lv_color_hex(0xF60202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_botaoReseta5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_botaoReseta5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_botaoReseta5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_botaoReseta5, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_botaoReseta5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label41 = lv_label_create(ui_botaoReseta5);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "x");

    ui_KeyboardExperimento = lv_keyboard_create(ui_ParametrosExperimento);
    lv_keyboard_set_mode(ui_KeyboardExperimento, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_KeyboardExperimento, 316);
    lv_obj_set_height(ui_KeyboardExperimento, 120);
    lv_obj_set_x(ui_KeyboardExperimento, 2);
    lv_obj_set_y(ui_KeyboardExperimento, 58);
    lv_obj_set_align(ui_KeyboardExperimento, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KeyboardExperimento, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_KeyboardExperimento, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_KeyboardExperimento, lv_color_hex(0x223E50), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KeyboardExperimento, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_KeyboardExperimento, 10, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_KeyboardExperimento, lv_color_hex(0x366381), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KeyboardExperimento, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_KeyboardExperimento, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_KeyboardExperimento, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_KeyboardExperimento, lv_color_hex(0xD5EFFF), LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_KeyboardExperimento, 255, LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_KeyboardExperimento, lv_color_hex(0x224359), LV_PART_ITEMS | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_KeyboardExperimento, 255, LV_PART_ITEMS | LV_STATE_PRESSED);
    lv_obj_set_style_outline_color(ui_KeyboardExperimento, lv_color_hex(0x009FC7), LV_PART_ITEMS | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_KeyboardExperimento, 255, LV_PART_ITEMS | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(ui_KeyboardExperimento, 3, LV_PART_ITEMS | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_KeyboardExperimento, 0, LV_PART_ITEMS | LV_STATE_PRESSED);
    lv_obj_set_style_text_color(ui_KeyboardExperimento, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_KeyboardExperimento, 255, LV_PART_ITEMS | LV_STATE_PRESSED);

    ui_botaoVolta3 = lv_btn_create(ui_ParametrosExperimento);
    lv_obj_set_width(ui_botaoVolta3, 25);
    lv_obj_set_height(ui_botaoVolta3, 25);
    lv_obj_set_x(ui_botaoVolta3, -141);
    lv_obj_set_y(ui_botaoVolta3, -104);
    lv_obj_set_align(ui_botaoVolta3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_botaoVolta3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_botaoVolta3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_botaoVolta3, lv_color_hex(0x1C13EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_botaoVolta3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_botaoVolta3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_botaoVolta3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_botaoVolta3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_botaoVolta3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_botaoVolta3);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "<");

    lv_obj_add_event_cb(ui_inputObserKe, ui_event_inputObserKe, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_inputRegulaK, ui_event_inputRegulaK, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_inputNEstados, ui_event_inputNEstados, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_inputNEntradas, ui_event_inputNEntradas, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_inputReferencia, ui_event_inputReferencia, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_botaoEnviaDados, ui_event_botaoEnviaDados, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_KeyboardExperimento, ui_inputObserKe);
    lv_obj_add_event_cb(ui_KeyboardExperimento, ui_event_KeyboardExperimento, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_botaoVolta3, ui_event_botaoVolta3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ParametrosExperimento, ui_event_ParametrosExperimento, LV_EVENT_ALL, NULL);

}

void ui_ParametrosExperimento_screen_destroy(void)
{
    if(ui_ParametrosExperimento) lv_obj_del(ui_ParametrosExperimento);

    // NULL screen variables
    ui_ParametrosExperimento = NULL;
    ui_painelIputs2 = NULL;
    ui_inputObserKe = NULL;
    ui_inputRegulaK = NULL;
    ui_inputNEstados = NULL;
    ui_inputNEntradas = NULL;
    ui_inputReferencia = NULL;
    ui_tituloTelaParametrosBroker2 = NULL;
    ui_botaoEnviaDados = NULL;
    ui_labelBotaoEnviaParametro = NULL;
    ui_Spinner4 = NULL;
    ui_botaoReseta5 = NULL;
    ui_Label41 = NULL;
    ui_KeyboardExperimento = NULL;
    ui_botaoVolta3 = NULL;
    ui_Label6 = NULL;

}
