// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: espDisplayUi

#include "ui.h"

lv_obj_t * ui_ConexaoWifiEspEstudante = NULL;
lv_obj_t * ui_painelIputs4 = NULL;
lv_obj_t * ui_inputWifiEstudante = NULL;
lv_obj_t * ui_inputEmailEstudante = NULL;
lv_obj_t * ui_inputsenhaEstudante = NULL;
lv_obj_t * ui_modoLocalRemoto3 = NULL;
lv_obj_t * ui_labelLocalRemoto3 = NULL;
lv_obj_t * ui_localRemoto3 = NULL;
lv_obj_t * ui_tituloTelaParametrosBroker4 = NULL;
lv_obj_t * ui_botaoConectaWifi2 = NULL;
lv_obj_t * ui_labelBotaoConecta3 = NULL;
lv_obj_t * ui_Spinner7 = NULL;
lv_obj_t * ui_botaoReseta2 = NULL;
lv_obj_t * ui_Label44 = NULL;
lv_obj_t * ui_KeyboardWifiCorporativo = NULL;
// event funtions
void ui_event_ConexaoWifiEspEstudante(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        _ui_flag_modify(ui_Spinner7, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_state_modify(ui_localRemoto3, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
}

void ui_event_inputWifiEstudante(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_KeyboardWifiCorporativo, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_KeyboardWifiCorporativo,  ui_inputWifiEstudante);
    }
}

void ui_event_inputEmailEstudante(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_KeyboardWifiCorporativo, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_KeyboardWifiCorporativo,  ui_inputEmailEstudante);
        _ui_basic_set_property(ui_painelIputs4, _UI_BASIC_PROPERTY_POSITION_Y,  -75);
        _ui_basic_set_property(ui_tituloTelaParametrosBroker4, _UI_BASIC_PROPERTY_POSITION_Y,  -150);
        _ui_basic_set_property(ui_botaoReseta2, _UI_BASIC_PROPERTY_POSITION_Y,  -150);
    }
}

void ui_event_inputsenhaEstudante(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_KeyboardWifiCorporativo, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_KeyboardWifiCorporativo,  ui_inputsenhaEstudante);
    }
}

void ui_event_localRemoto3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ConexaoWifiEspCaseira, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ConexaoWifiEspCaseira_screen_init);
        _ui_state_modify(ui_localRemoto3, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_botaoConectaWifi2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Spinner7, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_screen_change(&ui_ParametrosEspRemoto, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 8000, &ui_ParametrosEspRemoto_screen_init);
    }
}

void ui_event_botaoReseta2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Inicio, LV_SCR_LOAD_ANIM_OVER_RIGHT, 500, 0, &ui_Inicio_screen_init);
    }
}

void ui_event_KeyboardWifiCorporativo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_KeyboardWifiCorporativo, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_basic_set_property(ui_painelIputs4, _UI_BASIC_PROPERTY_POSITION_Y,  -8);
        _ui_basic_set_property(ui_tituloTelaParametrosBroker4, _UI_BASIC_PROPERTY_POSITION_Y,  -100);
        _ui_basic_set_property(ui_botaoReseta2, _UI_BASIC_PROPERTY_POSITION_Y,  -104);
    }
}

// build funtions

void ui_ConexaoWifiEspEstudante_screen_init(void)
{
    ui_ConexaoWifiEspEstudante = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ConexaoWifiEspEstudante,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_ConexaoWifiEspEstudante, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_ConexaoWifiEspEstudante, LV_DIR_TOP);
    lv_obj_set_scroll_snap_x(ui_ConexaoWifiEspEstudante, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_style_bg_color(ui_ConexaoWifiEspEstudante, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConexaoWifiEspEstudante, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_painelIputs4 = lv_obj_create(ui_ConexaoWifiEspEstudante);
    lv_obj_set_width(ui_painelIputs4, 300);
    lv_obj_set_height(ui_painelIputs4, 137);
    lv_obj_set_x(ui_painelIputs4, 0);
    lv_obj_set_y(ui_painelIputs4, -8);
    lv_obj_set_align(ui_painelIputs4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_painelIputs4, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);    /// Flags
    lv_obj_set_scrollbar_mode(ui_painelIputs4, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_painelIputs4, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_painelIputs4, lv_color_hex(0xE0DFFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_painelIputs4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_inputWifiEstudante = lv_textarea_create(ui_painelIputs4);
    lv_obj_set_width(ui_inputWifiEstudante, 250);
    lv_obj_set_height(ui_inputWifiEstudante, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_inputWifiEstudante, -8);
    lv_obj_set_y(ui_inputWifiEstudante, -11);
    lv_obj_set_align(ui_inputWifiEstudante, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_inputWifiEstudante, 100);
    lv_textarea_set_placeholder_text(ui_inputWifiEstudante, "Rede Wi-fi Institucional UFU");
    lv_textarea_set_one_line(ui_inputWifiEstudante, true);

    ui_inputEmailEstudante = lv_textarea_create(ui_painelIputs4);
    lv_obj_set_width(ui_inputEmailEstudante, 250);
    lv_obj_set_height(ui_inputEmailEstudante, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_inputEmailEstudante, -9);
    lv_obj_set_y(ui_inputEmailEstudante, 39);
    lv_obj_set_align(ui_inputEmailEstudante, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_inputEmailEstudante, 100);
    lv_textarea_set_placeholder_text(ui_inputEmailEstudante, "E-mail UFU");
    lv_textarea_set_one_line(ui_inputEmailEstudante, true);

    ui_inputsenhaEstudante = lv_textarea_create(ui_painelIputs4);
    lv_obj_set_width(ui_inputsenhaEstudante, 250);
    lv_obj_set_height(ui_inputsenhaEstudante, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_inputsenhaEstudante, -9);
    lv_obj_set_y(ui_inputsenhaEstudante, 94);
    lv_obj_set_align(ui_inputsenhaEstudante, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_inputsenhaEstudante, 100);
    lv_textarea_set_placeholder_text(ui_inputsenhaEstudante, "Senha do Portal ");
    lv_textarea_set_one_line(ui_inputsenhaEstudante, true);

    ui_modoLocalRemoto3 = lv_obj_create(ui_painelIputs4);
    lv_obj_remove_style_all(ui_modoLocalRemoto3);
    lv_obj_set_width(ui_modoLocalRemoto3, 281);
    lv_obj_set_height(ui_modoLocalRemoto3, 33);
    lv_obj_set_x(ui_modoLocalRemoto3, 0);
    lv_obj_set_y(ui_modoLocalRemoto3, -46);
    lv_obj_set_align(ui_modoLocalRemoto3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_modoLocalRemoto3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labelLocalRemoto3 = lv_label_create(ui_modoLocalRemoto3);
    lv_obj_set_width(ui_labelLocalRemoto3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelLocalRemoto3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelLocalRemoto3, -29);
    lv_obj_set_y(ui_labelLocalRemoto3, -2);
    lv_obj_set_align(ui_labelLocalRemoto3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelLocalRemoto3, "Utilizando rede corporativa?");

    ui_localRemoto3 = lv_switch_create(ui_modoLocalRemoto3);
    lv_obj_set_width(ui_localRemoto3, 50);
    lv_obj_set_height(ui_localRemoto3, 25);
    lv_obj_set_x(ui_localRemoto3, 112);
    lv_obj_set_y(ui_localRemoto3, -2);
    lv_obj_set_align(ui_localRemoto3, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_localRemoto3, lv_color_hex(0xABAAAD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_localRemoto3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_localRemoto3, lv_color_hex(0xE0DFFD), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_localRemoto3, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_localRemoto3, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_localRemoto3, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_localRemoto3, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_localRemoto3, 255, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_localRemoto3, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_localRemoto3, 255, LV_PART_KNOB | LV_STATE_PRESSED);

    ui_tituloTelaParametrosBroker4 = lv_label_create(ui_ConexaoWifiEspEstudante);
    lv_obj_set_width(ui_tituloTelaParametrosBroker4, 235);
    lv_obj_set_height(ui_tituloTelaParametrosBroker4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tituloTelaParametrosBroker4, 0);
    lv_obj_set_y(ui_tituloTelaParametrosBroker4, -100);
    lv_obj_set_align(ui_tituloTelaParametrosBroker4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tituloTelaParametrosBroker4, "Insira os dados abaixo para conectar a \nbancada na internet");
    lv_obj_set_style_text_align(ui_tituloTelaParametrosBroker4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tituloTelaParametrosBroker4, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_botaoConectaWifi2 = lv_btn_create(ui_ConexaoWifiEspEstudante);
    lv_obj_set_width(ui_botaoConectaWifi2, 174);
    lv_obj_set_height(ui_botaoConectaWifi2, 32);
    lv_obj_set_x(ui_botaoConectaWifi2, 61);
    lv_obj_set_y(ui_botaoConectaWifi2, 90);
    lv_obj_set_align(ui_botaoConectaWifi2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_botaoConectaWifi2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_botaoConectaWifi2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_botaoConectaWifi2, lv_color_hex(0x0FD93F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_botaoConectaWifi2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_botaoConectaWifi2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_botaoConectaWifi2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_botaoConectaWifi2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_botaoConectaWifi2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_botaoConectaWifi2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_botaoConectaWifi2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_botaoConectaWifi2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelBotaoConecta3 = lv_label_create(ui_botaoConectaWifi2);
    lv_obj_set_width(ui_labelBotaoConecta3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelBotaoConecta3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelBotaoConecta3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelBotaoConecta3, "Configurar o broker");

    ui_Spinner7 = lv_spinner_create(ui_ConexaoWifiEspEstudante, 1000, 90);
    lv_obj_set_width(ui_Spinner7, 33);
    lv_obj_set_height(ui_Spinner7, 26);
    lv_obj_set_x(ui_Spinner7, -126);
    lv_obj_set_y(ui_Spinner7, 92);
    lv_obj_set_align(ui_Spinner7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner7, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Spinner7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Spinner7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Spinner7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Spinner7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Spinner7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner7, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Spinner7, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner7, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner7, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_botaoReseta2 = lv_btn_create(ui_ConexaoWifiEspEstudante);
    lv_obj_set_width(ui_botaoReseta2, 25);
    lv_obj_set_height(ui_botaoReseta2, 25);
    lv_obj_set_x(ui_botaoReseta2, 141);
    lv_obj_set_y(ui_botaoReseta2, -104);
    lv_obj_set_align(ui_botaoReseta2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_botaoReseta2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_botaoReseta2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_botaoReseta2, lv_color_hex(0xF30606), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_botaoReseta2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_botaoReseta2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_botaoReseta2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_botaoReseta2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_botaoReseta2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label44 = lv_label_create(ui_botaoReseta2);
    lv_obj_set_width(ui_Label44, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label44, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label44, "x");

    ui_KeyboardWifiCorporativo = lv_keyboard_create(ui_ConexaoWifiEspEstudante);
    lv_obj_set_width(ui_KeyboardWifiCorporativo, 316);
    lv_obj_set_height(ui_KeyboardWifiCorporativo, 120);
    lv_obj_set_x(ui_KeyboardWifiCorporativo, 2);
    lv_obj_set_y(ui_KeyboardWifiCorporativo, 58);
    lv_obj_set_align(ui_KeyboardWifiCorporativo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KeyboardWifiCorporativo, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_KeyboardWifiCorporativo, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_KeyboardWifiCorporativo, lv_color_hex(0x223E50), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KeyboardWifiCorporativo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_KeyboardWifiCorporativo, 10, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_KeyboardWifiCorporativo, lv_color_hex(0x366381), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KeyboardWifiCorporativo, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_KeyboardWifiCorporativo, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_KeyboardWifiCorporativo, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_KeyboardWifiCorporativo, lv_color_hex(0xD5EFFF), LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_KeyboardWifiCorporativo, 255, LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_KeyboardWifiCorporativo, lv_color_hex(0x224359), LV_PART_ITEMS | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_KeyboardWifiCorporativo, 255, LV_PART_ITEMS | LV_STATE_PRESSED);
    lv_obj_set_style_outline_color(ui_KeyboardWifiCorporativo, lv_color_hex(0x009FC7), LV_PART_ITEMS | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_KeyboardWifiCorporativo, 255, LV_PART_ITEMS | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(ui_KeyboardWifiCorporativo, 3, LV_PART_ITEMS | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_KeyboardWifiCorporativo, 0, LV_PART_ITEMS | LV_STATE_PRESSED);
    lv_obj_set_style_text_color(ui_KeyboardWifiCorporativo, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_KeyboardWifiCorporativo, 255, LV_PART_ITEMS | LV_STATE_PRESSED);

    lv_obj_add_event_cb(ui_inputWifiEstudante, ui_event_inputWifiEstudante, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_inputEmailEstudante, ui_event_inputEmailEstudante, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_inputsenhaEstudante, ui_event_inputsenhaEstudante, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_localRemoto3, ui_event_localRemoto3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_botaoConectaWifi2, ui_event_botaoConectaWifi2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_botaoReseta2, ui_event_botaoReseta2, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_KeyboardWifiCorporativo, ui_inputWifiEstudante);
    lv_obj_add_event_cb(ui_KeyboardWifiCorporativo, ui_event_KeyboardWifiCorporativo, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ConexaoWifiEspEstudante, ui_event_ConexaoWifiEspEstudante, LV_EVENT_ALL, NULL);

}

void ui_ConexaoWifiEspEstudante_screen_destroy(void)
{
    if(ui_ConexaoWifiEspEstudante) lv_obj_del(ui_ConexaoWifiEspEstudante);

    // NULL screen variables
    ui_ConexaoWifiEspEstudante = NULL;
    ui_painelIputs4 = NULL;
    ui_inputWifiEstudante = NULL;
    ui_inputEmailEstudante = NULL;
    ui_inputsenhaEstudante = NULL;
    ui_modoLocalRemoto3 = NULL;
    ui_labelLocalRemoto3 = NULL;
    ui_localRemoto3 = NULL;
    ui_tituloTelaParametrosBroker4 = NULL;
    ui_botaoConectaWifi2 = NULL;
    ui_labelBotaoConecta3 = NULL;
    ui_Spinner7 = NULL;
    ui_botaoReseta2 = NULL;
    ui_Label44 = NULL;
    ui_KeyboardWifiCorporativo = NULL;

}
