// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: espDisplayUi

#ifndef UI_CONEXAOWIFIESPESTUDANTE_H
#define UI_CONEXAOWIFIESPESTUDANTE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ConexaoWifiEspEstudante
extern void ui_ConexaoWifiEspEstudante_screen_init(void);
extern void ui_ConexaoWifiEspEstudante_screen_destroy(void);
extern void ui_event_ConexaoWifiEspEstudante(lv_event_t * e);
extern lv_obj_t * ui_ConexaoWifiEspEstudante;
extern lv_obj_t * ui_painelIputs4;
extern void ui_event_inputWifiEstudante(lv_event_t * e);
extern lv_obj_t * ui_inputWifiEstudante;
extern void ui_event_inputEmailEstudante(lv_event_t * e);
extern lv_obj_t * ui_inputEmailEstudante;
extern void ui_event_inputsenhaEstudante(lv_event_t * e);
extern lv_obj_t * ui_inputsenhaEstudante;
extern lv_obj_t * ui_modoLocalRemoto3;
extern lv_obj_t * ui_labelLocalRemoto3;
extern void ui_event_localRemoto3(lv_event_t * e);
extern lv_obj_t * ui_localRemoto3;
extern lv_obj_t * ui_tituloTelaParametrosBroker4;
extern void ui_event_botaoConectaWifi2(lv_event_t * e);
extern lv_obj_t * ui_botaoConectaWifi2;
extern lv_obj_t * ui_labelBotaoConecta3;
extern lv_obj_t * ui_Spinner7;
extern void ui_event_botaoReseta2(lv_event_t * e);
extern lv_obj_t * ui_botaoReseta2;
extern lv_obj_t * ui_Label44;
extern void ui_event_KeyboardWifiCorporativo(lv_event_t * e);
extern lv_obj_t * ui_KeyboardWifiCorporativo;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

