// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: espDisplayUi

#include "ui.h"

lv_obj_t * ui_Inicio = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_botaoConfiguraRedeTela = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_botaoAjustereservatorioTela = NULL;
lv_obj_t * ui_Label12 = NULL;
// event funtions
void ui_event_botaoConfiguraRedeTela(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ConexaoWifiEspCaseira, LV_SCR_LOAD_ANIM_OVER_RIGHT, 500, 0,
                          &ui_ConexaoWifiEspCaseira_screen_init);
    }
}

void ui_event_botaoAjustereservatorioTela(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ConexaoWifiEspCaseira, LV_SCR_LOAD_ANIM_OVER_RIGHT, 500, 0,
                          &ui_ConexaoWifiEspCaseira_screen_init);
    }
}

// build funtions

void ui_Inicio_screen_init(void)
{
    ui_Inicio = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Inicio, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label10 = lv_label_create(ui_Inicio);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -1);
    lv_obj_set_y(ui_Label10, -91);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Boas vindas !");

    ui_Label3 = lv_label_create(ui_Inicio);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -2);
    lv_obj_set_y(ui_Label3, -24);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3,
                      "Esta bancada tem como objetivo aplicar\nos conhecimentos sobre Espaco de\nEstados para os estudantes de \nengenharia da UFU");
    lv_obj_set_style_text_align(ui_Label3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Inicio);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -3);
    lv_obj_set_y(ui_Label7, 104);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7,
                      "\"Se voce tem conhecimento, deixe que outros acendam \nsuas velas com ele\" - Margaret Fuller");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_botaoConfiguraRedeTela = lv_btn_create(ui_Inicio);
    lv_obj_set_width(ui_botaoConfiguraRedeTela, 120);
    lv_obj_set_height(ui_botaoConfiguraRedeTela, 50);
    lv_obj_set_x(ui_botaoConfiguraRedeTela, 86);
    lv_obj_set_y(ui_botaoConfiguraRedeTela, 49);
    lv_obj_set_align(ui_botaoConfiguraRedeTela, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_botaoConfiguraRedeTela, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_botaoConfiguraRedeTela, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_botaoConfiguraRedeTela, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_botaoConfiguraRedeTela, lv_color_hex(0x0FD93F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_botaoConfiguraRedeTela, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_botaoConfiguraRedeTela, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_botaoConfiguraRedeTela, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_botaoConfiguraRedeTela, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_botaoConfiguraRedeTela, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_botaoConfiguraRedeTela);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Configurar\nRede");
    lv_obj_set_style_text_align(ui_Label11, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_botaoAjustereservatorioTela = lv_btn_create(ui_Inicio);
    lv_obj_set_width(ui_botaoAjustereservatorioTela, 120);
    lv_obj_set_height(ui_botaoAjustereservatorioTela, 50);
    lv_obj_set_x(ui_botaoAjustereservatorioTela, -86);
    lv_obj_set_y(ui_botaoAjustereservatorioTela, 48);
    lv_obj_set_align(ui_botaoAjustereservatorioTela, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_botaoAjustereservatorioTela, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_botaoAjustereservatorioTela, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_botaoAjustereservatorioTela, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_botaoAjustereservatorioTela, lv_color_hex(0x1C13EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_botaoAjustereservatorioTela, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_botaoAjustereservatorioTela, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_botaoAjustereservatorioTela, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_botaoAjustereservatorioTela, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_botaoAjustereservatorioTela, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_botaoAjustereservatorioTela);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Ajuste dos\nReservatorios");
    lv_obj_set_style_text_align(ui_Label12, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_botaoConfiguraRedeTela, ui_event_botaoConfiguraRedeTela, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_botaoAjustereservatorioTela, ui_event_botaoAjustereservatorioTela, LV_EVENT_ALL, NULL);

}

void ui_Inicio_screen_destroy(void)
{
    if(ui_Inicio) lv_obj_del(ui_Inicio);

    // NULL screen variables
    ui_Inicio = NULL;
    ui_Label10 = NULL;
    ui_Label3 = NULL;
    ui_Label7 = NULL;
    ui_botaoConfiguraRedeTela = NULL;
    ui_Label11 = NULL;
    ui_botaoAjustereservatorioTela = NULL;
    ui_Label12 = NULL;

}
