// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: espDisplayUi

#ifndef UI_PARAMETROSESPREMOTO_H
#define UI_PARAMETROSESPREMOTO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ParametrosEspRemoto
extern void ui_ParametrosEspRemoto_screen_init(void);
extern void ui_ParametrosEspRemoto_screen_destroy(void);
extern void ui_event_ParametrosEspRemoto(lv_event_t * e);
extern lv_obj_t * ui_ParametrosEspRemoto;
extern lv_obj_t * ui_painelIputs;
extern void ui_event_inputIP(lv_event_t * e);
extern lv_obj_t * ui_inputIP;
extern void ui_event_inputPorta(lv_event_t * e);
extern lv_obj_t * ui_inputPorta;
extern lv_obj_t * ui_modoLocalRemoto;
extern lv_obj_t * ui_labelLocalRemoto;
extern void ui_event_localRemoto(lv_event_t * e);
extern lv_obj_t * ui_localRemoto;
extern lv_obj_t * ui_tituloTelaParametrosBroker;
extern void ui_event_botaoConectaBroker1(lv_event_t * e);
extern lv_obj_t * ui_botaoConectaBroker1;
extern lv_obj_t * ui_labelBotaoConecta;
extern lv_obj_t * ui_Spinner2;
extern void ui_event_botaoReseta3(lv_event_t * e);
extern lv_obj_t * ui_botaoReseta3;
extern lv_obj_t * ui_Label38;
extern void ui_event_KeyboardEspRemoto(lv_event_t * e);
extern lv_obj_t * ui_KeyboardEspRemoto;
extern void ui_event_botaoVolta1(lv_event_t * e);
extern lv_obj_t * ui_botaoVolta1;
extern lv_obj_t * ui_Label1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

