// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: espDisplayUi

#ifndef UI_PRIMEIRA_TELA_H
#define UI_PRIMEIRA_TELA_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Primeira_Tela
extern void ui_Primeira_Tela_screen_init(void);
extern void ui_Primeira_Tela_screen_destroy(void);
extern void ui_event_PrimeiraTela(lv_event_t * e);
extern lv_obj_t * ui_PrimeiraTela;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

