// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: espDisplayUi

#include "ui.h"

lv_obj_t * ui_ParametrosEspLocal = NULL;
lv_obj_t * ui_painelIputs1 = NULL;
lv_obj_t * ui_inputIP1 = NULL;
lv_obj_t * ui_inputPorta1 = NULL;
lv_obj_t * ui_modoLocalRemoto1 = NULL;
lv_obj_t * ui_labelLocalRemoto1 = NULL;
lv_obj_t * ui_localRemoto1 = NULL;
lv_obj_t * ui_tituloTelaParametrosBroker1 = NULL;
lv_obj_t * ui_botaoConectaBroker2 = NULL;
lv_obj_t * ui_labelBotaoConecta1 = NULL;
lv_obj_t * ui_Spinner3 = NULL;
lv_obj_t * ui_botaoReseta4 = NULL;
lv_obj_t * ui_Label40 = NULL;
lv_obj_t * ui_KeyboardEspLocal = NULL;
lv_obj_t * ui_botaoVolta2 = NULL;
lv_obj_t * ui_Label5 = NULL;
// event funtions
void ui_event_ParametrosEspLocal(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        _ui_flag_modify(ui_Spinner3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_state_modify(ui_localRemoto1, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
}

void ui_event_inputIP1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_KeyboardEspLocal, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_KeyboardEspLocal,  ui_inputIP1);
    }
}

void ui_event_inputPorta1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_KeyboardEspLocal, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_KeyboardEspLocal,  ui_inputPorta1);
        _ui_basic_set_property(ui_painelIputs1, _UI_BASIC_PROPERTY_POSITION_Y,  -75);
        _ui_basic_set_property(ui_tituloTelaParametrosBroker1, _UI_BASIC_PROPERTY_POSITION_Y,  -150);
        _ui_basic_set_property(ui_botaoReseta4, _UI_BASIC_PROPERTY_POSITION_Y,  -150);
        _ui_basic_set_property(ui_botaoVolta2, _UI_BASIC_PROPERTY_POSITION_Y,  -150);
    }
}

void ui_event_localRemoto1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ParametrosEspRemoto, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ParametrosEspRemoto_screen_init);
    }
}

void ui_event_botaoConectaBroker2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Spinner3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_screen_change(&ui_ParametrosExperimento, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 8000,
                          &ui_ParametrosExperimento_screen_init);
    }
}

void ui_event_botaoReseta4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Inicio, LV_SCR_LOAD_ANIM_OVER_RIGHT, 500, 0, &ui_Inicio_screen_init);
    }
}

void ui_event_KeyboardEspLocal(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_KeyboardEspLocal, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_basic_set_property(ui_painelIputs1, _UI_BASIC_PROPERTY_POSITION_Y,  -8);
        _ui_basic_set_property(ui_tituloTelaParametrosBroker1, _UI_BASIC_PROPERTY_POSITION_Y,  -100);
        _ui_basic_set_property(ui_botaoReseta4, _UI_BASIC_PROPERTY_POSITION_Y,  -104);
        _ui_basic_set_property(ui_botaoVolta2, _UI_BASIC_PROPERTY_POSITION_Y,  -104);
    }
}

void ui_event_botaoVolta2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ConexaoWifiEspCaseira, LV_SCR_LOAD_ANIM_OVER_RIGHT, 500, 0,
                          &ui_ConexaoWifiEspCaseira_screen_init);
    }
}

// build funtions

void ui_ParametrosEspLocal_screen_init(void)
{
    ui_ParametrosEspLocal = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ParametrosEspLocal,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_ParametrosEspLocal, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_snap_x(ui_ParametrosEspLocal, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_style_bg_color(ui_ParametrosEspLocal, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ParametrosEspLocal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_painelIputs1 = lv_obj_create(ui_ParametrosEspLocal);
    lv_obj_set_width(ui_painelIputs1, 300);
    lv_obj_set_height(ui_painelIputs1, 137);
    lv_obj_set_x(ui_painelIputs1, 0);
    lv_obj_set_y(ui_painelIputs1, -8);
    lv_obj_set_align(ui_painelIputs1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_painelIputs1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_painelIputs1, lv_color_hex(0xE0DFFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_painelIputs1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_inputIP1 = lv_textarea_create(ui_painelIputs1);
    lv_obj_set_width(ui_inputIP1, 250);
    lv_obj_set_height(ui_inputIP1, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_inputIP1, -18);
    lv_obj_set_y(ui_inputIP1, -41);
    lv_obj_set_align(ui_inputIP1, LV_ALIGN_CENTER);
    if("123456789." == "") lv_textarea_set_accepted_chars(ui_inputIP1, NULL);
    else lv_textarea_set_accepted_chars(ui_inputIP1, "123456789.");
    lv_textarea_set_max_length(ui_inputIP1, 15);
    lv_textarea_set_placeholder_text(ui_inputIP1, "IP do Broker");
    lv_textarea_set_one_line(ui_inputIP1, true);

    ui_inputPorta1 = lv_textarea_create(ui_painelIputs1);
    lv_obj_set_width(ui_inputPorta1, 181);
    lv_obj_set_height(ui_inputPorta1, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_inputPorta1, -50);
    lv_obj_set_y(ui_inputPorta1, 6);
    lv_obj_set_align(ui_inputPorta1, LV_ALIGN_CENTER);
    if("123456789" == "") lv_textarea_set_accepted_chars(ui_inputPorta1, NULL);
    else lv_textarea_set_accepted_chars(ui_inputPorta1, "123456789");
    lv_textarea_set_max_length(ui_inputPorta1, 4);
    lv_textarea_set_placeholder_text(ui_inputPorta1, "Porta do Broker");
    lv_textarea_set_one_line(ui_inputPorta1, true);

    ui_modoLocalRemoto1 = lv_obj_create(ui_painelIputs1);
    lv_obj_remove_style_all(ui_modoLocalRemoto1);
    lv_obj_set_width(ui_modoLocalRemoto1, 298);
    lv_obj_set_height(ui_modoLocalRemoto1, 33);
    lv_obj_set_x(ui_modoLocalRemoto1, 1);
    lv_obj_set_y(ui_modoLocalRemoto1, 47);
    lv_obj_set_align(ui_modoLocalRemoto1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_modoLocalRemoto1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labelLocalRemoto1 = lv_label_create(ui_modoLocalRemoto1);
    lv_obj_set_width(ui_labelLocalRemoto1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelLocalRemoto1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelLocalRemoto1, -29);
    lv_obj_set_y(ui_labelLocalRemoto1, -2);
    lv_obj_set_align(ui_labelLocalRemoto1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelLocalRemoto1, "Experimento em modo local?");

    ui_localRemoto1 = lv_switch_create(ui_modoLocalRemoto1);
    lv_obj_set_width(ui_localRemoto1, 50);
    lv_obj_set_height(ui_localRemoto1, 25);
    lv_obj_set_x(ui_localRemoto1, 119);
    lv_obj_set_y(ui_localRemoto1, -2);
    lv_obj_set_align(ui_localRemoto1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_localRemoto1, lv_color_hex(0xABAAAD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_localRemoto1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_localRemoto1, lv_color_hex(0xE0DFFD), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_localRemoto1, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_localRemoto1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_localRemoto1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_localRemoto1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_localRemoto1, 255, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_localRemoto1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_localRemoto1, 255, LV_PART_KNOB | LV_STATE_PRESSED);

    ui_tituloTelaParametrosBroker1 = lv_label_create(ui_ParametrosEspLocal);
    lv_obj_set_width(ui_tituloTelaParametrosBroker1, 235);
    lv_obj_set_height(ui_tituloTelaParametrosBroker1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tituloTelaParametrosBroker1, 0);
    lv_obj_set_y(ui_tituloTelaParametrosBroker1, -99);
    lv_obj_set_align(ui_tituloTelaParametrosBroker1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tituloTelaParametrosBroker1, "Insira os dados abaixo para conectar a \nbancada ao broker");
    lv_obj_set_style_text_align(ui_tituloTelaParametrosBroker1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tituloTelaParametrosBroker1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_botaoConectaBroker2 = lv_btn_create(ui_ParametrosEspLocal);
    lv_obj_set_width(ui_botaoConectaBroker2, 174);
    lv_obj_set_height(ui_botaoConectaBroker2, 32);
    lv_obj_set_x(ui_botaoConectaBroker2, 61);
    lv_obj_set_y(ui_botaoConectaBroker2, 90);
    lv_obj_set_align(ui_botaoConectaBroker2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_botaoConectaBroker2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_botaoConectaBroker2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_botaoConectaBroker2, lv_color_hex(0x0FD93F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_botaoConectaBroker2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_botaoConectaBroker2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_botaoConectaBroker2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_botaoConectaBroker2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_botaoConectaBroker2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_botaoConectaBroker2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_botaoConectaBroker2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_botaoConectaBroker2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelBotaoConecta1 = lv_label_create(ui_botaoConectaBroker2);
    lv_obj_set_width(ui_labelBotaoConecta1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelBotaoConecta1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelBotaoConecta1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelBotaoConecta1, "Inserir dados ");

    ui_Spinner3 = lv_spinner_create(ui_ParametrosEspLocal, 1000, 90);
    lv_obj_set_width(ui_Spinner3, 33);
    lv_obj_set_height(ui_Spinner3, 26);
    lv_obj_set_x(ui_Spinner3, -126);
    lv_obj_set_y(ui_Spinner3, 92);
    lv_obj_set_align(ui_Spinner3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner3, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Spinner3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Spinner3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Spinner3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Spinner3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Spinner3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Spinner3, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner3, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_botaoReseta4 = lv_btn_create(ui_ParametrosEspLocal);
    lv_obj_set_width(ui_botaoReseta4, 25);
    lv_obj_set_height(ui_botaoReseta4, 25);
    lv_obj_set_x(ui_botaoReseta4, 141);
    lv_obj_set_y(ui_botaoReseta4, -103);
    lv_obj_set_align(ui_botaoReseta4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_botaoReseta4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_botaoReseta4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_botaoReseta4, lv_color_hex(0xF30404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_botaoReseta4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_botaoReseta4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_botaoReseta4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_botaoReseta4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_botaoReseta4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label40 = lv_label_create(ui_botaoReseta4);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label40, "x");

    ui_KeyboardEspLocal = lv_keyboard_create(ui_ParametrosEspLocal);
    lv_keyboard_set_mode(ui_KeyboardEspLocal, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_KeyboardEspLocal, 316);
    lv_obj_set_height(ui_KeyboardEspLocal, 120);
    lv_obj_set_x(ui_KeyboardEspLocal, 2);
    lv_obj_set_y(ui_KeyboardEspLocal, 58);
    lv_obj_set_align(ui_KeyboardEspLocal, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KeyboardEspLocal, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_KeyboardEspLocal, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_KeyboardEspLocal, lv_color_hex(0x223E50), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KeyboardEspLocal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_KeyboardEspLocal, 10, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_KeyboardEspLocal, lv_color_hex(0x366381), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KeyboardEspLocal, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_KeyboardEspLocal, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_KeyboardEspLocal, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_KeyboardEspLocal, lv_color_hex(0xD5EFFF), LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_KeyboardEspLocal, 255, LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_KeyboardEspLocal, lv_color_hex(0x224359), LV_PART_ITEMS | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_KeyboardEspLocal, 255, LV_PART_ITEMS | LV_STATE_PRESSED);
    lv_obj_set_style_outline_color(ui_KeyboardEspLocal, lv_color_hex(0x009FC7), LV_PART_ITEMS | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_KeyboardEspLocal, 255, LV_PART_ITEMS | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(ui_KeyboardEspLocal, 3, LV_PART_ITEMS | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_KeyboardEspLocal, 0, LV_PART_ITEMS | LV_STATE_PRESSED);
    lv_obj_set_style_text_color(ui_KeyboardEspLocal, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_KeyboardEspLocal, 255, LV_PART_ITEMS | LV_STATE_PRESSED);

    ui_botaoVolta2 = lv_btn_create(ui_ParametrosEspLocal);
    lv_obj_set_width(ui_botaoVolta2, 25);
    lv_obj_set_height(ui_botaoVolta2, 25);
    lv_obj_set_x(ui_botaoVolta2, -141);
    lv_obj_set_y(ui_botaoVolta2, -104);
    lv_obj_set_align(ui_botaoVolta2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_botaoVolta2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_botaoVolta2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_botaoVolta2, lv_color_hex(0x1C13EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_botaoVolta2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_botaoVolta2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_botaoVolta2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_botaoVolta2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_botaoVolta2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_botaoVolta2);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "<");

    lv_obj_add_event_cb(ui_inputIP1, ui_event_inputIP1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_inputPorta1, ui_event_inputPorta1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_localRemoto1, ui_event_localRemoto1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_botaoConectaBroker2, ui_event_botaoConectaBroker2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_botaoReseta4, ui_event_botaoReseta4, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_KeyboardEspLocal, ui_inputIP1);
    lv_obj_add_event_cb(ui_KeyboardEspLocal, ui_event_KeyboardEspLocal, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_botaoVolta2, ui_event_botaoVolta2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ParametrosEspLocal, ui_event_ParametrosEspLocal, LV_EVENT_ALL, NULL);

}

void ui_ParametrosEspLocal_screen_destroy(void)
{
    if(ui_ParametrosEspLocal) lv_obj_del(ui_ParametrosEspLocal);

    // NULL screen variables
    ui_ParametrosEspLocal = NULL;
    ui_painelIputs1 = NULL;
    ui_inputIP1 = NULL;
    ui_inputPorta1 = NULL;
    ui_modoLocalRemoto1 = NULL;
    ui_labelLocalRemoto1 = NULL;
    ui_localRemoto1 = NULL;
    ui_tituloTelaParametrosBroker1 = NULL;
    ui_botaoConectaBroker2 = NULL;
    ui_labelBotaoConecta1 = NULL;
    ui_Spinner3 = NULL;
    ui_botaoReseta4 = NULL;
    ui_Label40 = NULL;
    ui_KeyboardEspLocal = NULL;
    ui_botaoVolta2 = NULL;
    ui_Label5 = NULL;

}
