// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: espDisplayUi

#ifndef UI_RESERVATORIOS_H
#define UI_RESERVATORIOS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Reservatorios
extern void ui_Reservatorios_screen_init(void);
extern void ui_Reservatorios_screen_destroy(void);
extern lv_obj_t * ui_Reservatorios;
extern lv_obj_t * ui_botaoEncheReservatorio;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_botaoEsvaziaReservatorio;
extern lv_obj_t * ui_Label14;
extern void ui_event_botaoConfiguraRedeTela2(lv_event_t * e);
extern lv_obj_t * ui_botaoConfiguraRedeTela2;
extern lv_obj_t * ui_Label16;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

