// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: espDisplayUi

#include "ui.h"

lv_obj_t * ui_Reservatorios = NULL;
lv_obj_t * ui_botaoEncheReservatorio = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_botaoEsvaziaReservatorio = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_botaoConfiguraRedeTela2 = NULL;
lv_obj_t * ui_Label16 = NULL;
// event funtions
void ui_event_botaoConfiguraRedeTela2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ConexaoWifiEspCaseira, LV_SCR_LOAD_ANIM_OVER_RIGHT, 500, 0,
                          &ui_ConexaoWifiEspCaseira_screen_init);
    }
}

// build funtions

void ui_Reservatorios_screen_init(void)
{
    ui_Reservatorios = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Reservatorios, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_botaoEncheReservatorio = lv_btn_create(ui_Reservatorios);
    lv_obj_set_width(ui_botaoEncheReservatorio, 120);
    lv_obj_set_height(ui_botaoEncheReservatorio, 50);
    lv_obj_set_x(ui_botaoEncheReservatorio, 0);
    lv_obj_set_y(ui_botaoEncheReservatorio, -75);
    lv_obj_set_align(ui_botaoEncheReservatorio, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_botaoEncheReservatorio, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_botaoEncheReservatorio, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_botaoEncheReservatorio, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_botaoEncheReservatorio, lv_color_hex(0x1C13EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_botaoEncheReservatorio, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_botaoEncheReservatorio, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_botaoEncheReservatorio, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_botaoEncheReservatorio, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_botaoEncheReservatorio, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_botaoEncheReservatorio);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Encher\nreservatorios");
    lv_obj_set_style_text_align(ui_Label13, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_botaoEsvaziaReservatorio = lv_btn_create(ui_Reservatorios);
    lv_obj_set_width(ui_botaoEsvaziaReservatorio, 120);
    lv_obj_set_height(ui_botaoEsvaziaReservatorio, 50);
    lv_obj_set_x(ui_botaoEsvaziaReservatorio, 0);
    lv_obj_set_y(ui_botaoEsvaziaReservatorio, -1);
    lv_obj_set_align(ui_botaoEsvaziaReservatorio, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_botaoEsvaziaReservatorio, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_botaoEsvaziaReservatorio, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_botaoEsvaziaReservatorio, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_botaoEsvaziaReservatorio, lv_color_hex(0xF60202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_botaoEsvaziaReservatorio, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_botaoEsvaziaReservatorio, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_botaoEsvaziaReservatorio, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_botaoEsvaziaReservatorio, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_botaoEsvaziaReservatorio, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_botaoEsvaziaReservatorio);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Esvaziar\nreservatorios");
    lv_obj_set_style_text_align(ui_Label14, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_botaoConfiguraRedeTela2 = lv_btn_create(ui_Reservatorios);
    lv_obj_set_width(ui_botaoConfiguraRedeTela2, 120);
    lv_obj_set_height(ui_botaoConfiguraRedeTela2, 50);
    lv_obj_set_x(ui_botaoConfiguraRedeTela2, 1);
    lv_obj_set_y(ui_botaoConfiguraRedeTela2, 74);
    lv_obj_set_align(ui_botaoConfiguraRedeTela2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_botaoConfiguraRedeTela2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_botaoConfiguraRedeTela2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_botaoConfiguraRedeTela2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_botaoConfiguraRedeTela2, lv_color_hex(0x0FD93F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_botaoConfiguraRedeTela2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_botaoConfiguraRedeTela2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_botaoConfiguraRedeTela2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_botaoConfiguraRedeTela2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_botaoConfiguraRedeTela2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_botaoConfiguraRedeTela2);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Configurar\nRede");
    lv_obj_set_style_text_align(ui_Label16, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_botaoConfiguraRedeTela2, ui_event_botaoConfiguraRedeTela2, LV_EVENT_ALL, NULL);

}

void ui_Reservatorios_screen_destroy(void)
{
    if(ui_Reservatorios) lv_obj_del(ui_Reservatorios);

    // NULL screen variables
    ui_Reservatorios = NULL;
    ui_botaoEncheReservatorio = NULL;
    ui_Label13 = NULL;
    ui_botaoEsvaziaReservatorio = NULL;
    ui_Label14 = NULL;
    ui_botaoConfiguraRedeTela2 = NULL;
    ui_Label16 = NULL;

}
