// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: espDisplayUi

#include "ui.h"

lv_obj_t * ui_Sucesso = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_botaoVolta4 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_botaoReseta6 = NULL;
lv_obj_t * ui_Label9 = NULL;
// event funtions
void ui_event_botaoVolta4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Inicio, LV_SCR_LOAD_ANIM_OVER_RIGHT, 500, 0, &ui_Inicio_screen_init);
    }
}

void ui_event_botaoReseta6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Inicio, LV_SCR_LOAD_ANIM_OVER_RIGHT, 500, 0, &ui_Inicio_screen_init);
    }
}

// build funtions

void ui_Sucesso_screen_init(void)
{
    ui_Sucesso = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Sucesso, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_Sucesso);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 2);
    lv_obj_set_y(ui_Label2, 4);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Dados enviados com sucesso!\n\n\n\nPode voltar ou encerrar o experimento");
    lv_obj_set_style_text_align(ui_Label2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_botaoVolta4 = lv_btn_create(ui_Sucesso);
    lv_obj_set_width(ui_botaoVolta4, 25);
    lv_obj_set_height(ui_botaoVolta4, 25);
    lv_obj_set_x(ui_botaoVolta4, -141);
    lv_obj_set_y(ui_botaoVolta4, -104);
    lv_obj_set_align(ui_botaoVolta4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_botaoVolta4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_botaoVolta4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_botaoVolta4, lv_color_hex(0x1C13EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_botaoVolta4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_botaoVolta4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_botaoVolta4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_botaoVolta4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_botaoVolta4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_botaoVolta4);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "<");

    ui_botaoReseta6 = lv_btn_create(ui_Sucesso);
    lv_obj_set_width(ui_botaoReseta6, 25);
    lv_obj_set_height(ui_botaoReseta6, 25);
    lv_obj_set_x(ui_botaoReseta6, 145);
    lv_obj_set_y(ui_botaoReseta6, -106);
    lv_obj_set_align(ui_botaoReseta6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_botaoReseta6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_botaoReseta6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_botaoReseta6, lv_color_hex(0xF60202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_botaoReseta6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_botaoReseta6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_botaoReseta6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_botaoReseta6, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_botaoReseta6, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_botaoReseta6);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "x");

    lv_obj_add_event_cb(ui_botaoVolta4, ui_event_botaoVolta4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_botaoReseta6, ui_event_botaoReseta6, LV_EVENT_ALL, NULL);

}

void ui_Sucesso_screen_destroy(void)
{
    if(ui_Sucesso) lv_obj_del(ui_Sucesso);

    // NULL screen variables
    ui_Sucesso = NULL;
    ui_Label2 = NULL;
    ui_botaoVolta4 = NULL;
    ui_Label8 = NULL;
    ui_botaoReseta6 = NULL;
    ui_Label9 = NULL;

}
