// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: espDisplayUi

#ifndef _ESPDISPLAYUI_UI_H
#define _ESPDISPLAYUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "ui_PrimeiraTela.h"
#include "ui_SplashScreen.h"
#include "ui_ParametrosEspRemoto.h"
#include "ui_ParametrosEspLocal.h"
#include "ui_ParametrosExperimento.h"
#include "ui_ConexaoWifiEspCaseira.h"
#include "ui_ConexaoWifiEspEstudante.h"
#include "ui_Sucesso.h"
#include "ui_Inicio.h"
#include "ui_Reservatorios.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_logo_ufu_png);    // assets/Logo UFU.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
