// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: espDisplayUi

#ifndef UI_CONEXAOWIFIESPCASEIRA_H
#define UI_CONEXAOWIFIESPCASEIRA_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ConexaoWifiEspCaseira
extern void ui_ConexaoWifiEspCaseira_screen_init(void);
extern void ui_ConexaoWifiEspCaseira_screen_destroy(void);
extern void ui_event_ConexaoWifiEspCaseira(lv_event_t * e);
extern lv_obj_t * ui_ConexaoWifiEspCaseira;
extern lv_obj_t * ui_painelIputs3;
extern void ui_event_inputWifi(lv_event_t * e);
extern lv_obj_t * ui_inputWifi;
extern void ui_event_inputSenhaC(lv_event_t * e);
extern lv_obj_t * ui_inputSenhaC;
extern lv_obj_t * ui_modoLocalRemoto2;
extern lv_obj_t * ui_labelLocalRemoto2;
extern void ui_event_caseiraEstudante(lv_event_t * e);
extern lv_obj_t * ui_caseiraEstudante;
extern lv_obj_t * ui_tituloTelaParametrosBroker3;
extern void ui_event_botaoConectaWifi1(lv_event_t * e);
extern lv_obj_t * ui_botaoConectaWifi1;
extern lv_obj_t * ui_labelBotaoConecta2;
extern lv_obj_t * ui_Spinner6;
extern void ui_event_botaoReseta1(lv_event_t * e);
extern lv_obj_t * ui_botaoReseta1;
extern lv_obj_t * ui_Label43;
extern void ui_event_KeyboardWifiCaseira(lv_event_t * e);
extern lv_obj_t * ui_KeyboardWifiCaseira;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

