// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: espDisplayUi

#ifndef UI_INICIO_H
#define UI_INICIO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Inicio
extern void ui_Inicio_screen_init(void);
extern void ui_Inicio_screen_destroy(void);
extern lv_obj_t * ui_Inicio;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label7;
extern void ui_event_botaoConfiguraRedeTela(lv_event_t * e);
extern lv_obj_t * ui_botaoConfiguraRedeTela;
extern lv_obj_t * ui_Label11;
extern void ui_event_botaoAjustereservatorioTela(lv_event_t * e);
extern lv_obj_t * ui_botaoAjustereservatorioTela;
extern lv_obj_t * ui_Label12;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

