// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: espDisplayUi

#ifndef UI_PARAMETROSESPLOCAL_H
#define UI_PARAMETROSESPLOCAL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ParametrosEspLocal
extern void ui_ParametrosEspLocal_screen_init(void);
extern void ui_ParametrosEspLocal_screen_destroy(void);
extern void ui_event_ParametrosEspLocal(lv_event_t * e);
extern lv_obj_t * ui_ParametrosEspLocal;
extern lv_obj_t * ui_painelIputs1;
extern void ui_event_inputIP1(lv_event_t * e);
extern lv_obj_t * ui_inputIP1;
extern void ui_event_inputPorta1(lv_event_t * e);
extern lv_obj_t * ui_inputPorta1;
extern lv_obj_t * ui_modoLocalRemoto1;
extern lv_obj_t * ui_labelLocalRemoto1;
extern void ui_event_localRemoto1(lv_event_t * e);
extern lv_obj_t * ui_localRemoto1;
extern lv_obj_t * ui_tituloTelaParametrosBroker1;
extern void ui_event_botaoConectaBroker2(lv_event_t * e);
extern lv_obj_t * ui_botaoConectaBroker2;
extern lv_obj_t * ui_labelBotaoConecta1;
extern lv_obj_t * ui_Spinner3;
extern void ui_event_botaoReseta4(lv_event_t * e);
extern lv_obj_t * ui_botaoReseta4;
extern lv_obj_t * ui_Label40;
extern void ui_event_KeyboardEspLocal(lv_event_t * e);
extern lv_obj_t * ui_KeyboardEspLocal;
extern void ui_event_botaoVolta2(lv_event_t * e);
extern lv_obj_t * ui_botaoVolta2;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

