// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: espDisplayUi

#ifndef UI_SUCESSO_H
#define UI_SUCESSO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Sucesso
extern void ui_Sucesso_screen_init(void);
extern void ui_Sucesso_screen_destroy(void);
extern lv_obj_t * ui_Sucesso;
extern lv_obj_t * ui_Label2;
extern void ui_event_botaoVolta4(lv_event_t * e);
extern lv_obj_t * ui_botaoVolta4;
extern lv_obj_t * ui_Label8;
extern void ui_event_botaoReseta6(lv_event_t * e);
extern lv_obj_t * ui_botaoReseta6;
extern lv_obj_t * ui_Label9;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

