// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: espDisplayUi

#ifndef UI_INICIALSCREEN_H
#define UI_INICIALSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_InicialScreen
extern void ui_InicialScreen_screen_init(void);
extern void ui_InicialScreen_screen_destroy(void);
extern void ui_event_TelaInicial(lv_event_t * e);
extern lv_obj_t * ui_TelaInicial;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

