// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: espDisplayUi

#include "ui.h"

lv_obj_t * ui_InicialScreen = NULL;
// event funtions
void ui_event_InicialScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_SplashScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 2000, &ui_SplashScreen_screen_init);
    }
}

// build funtions

void ui_InicialScreen_screen_init(void)
{
    ui_InicialScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_InicialScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_InicialScreen, ui_event_InicialScreen, LV_EVENT_ALL, NULL);

}

void ui_InicialScreen_screen_destroy(void)
{
    if(ui_InicialScreen) lv_obj_del(ui_InicialScreen);

    // NULL screen variables
    ui_InicialScreen = NULL;

}
