// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: espDisplayUi

#ifndef UI_PARAMETROSESPLOCAL_H
#define UI_PARAMETROSESPLOCAL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ParametrosEspLocal
extern void ui_ParametrosEspLocal_screen_init(void);
extern void ui_ParametrosEspLocal_screen_destroy(void);
extern void ui_event_ParametrosEspLocal(lv_event_t * e);
extern lv_obj_t * ui_ParametrosEspLocal;
extern lv_obj_t * ui_painelIputs1;
extern void ui_event_inputIP1(lv_event_t * e);
extern lv_obj_t * ui_inputIP1;
extern void ui_event_inputPorta1(lv_event_t * e);
extern lv_obj_t * ui_inputPorta1;
extern lv_obj_t * ui_modoLocalRemoto1;
extern lv_obj_t * ui_labelLocalRemoto1;
extern void ui_event_localRemoto1(lv_event_t * e);
extern lv_obj_t * ui_localRemoto1;
extern lv_obj_t * ui_tituloTelaParametrosBroker1;
extern void ui_event_conectaBroker1(lv_event_t * e);
extern lv_obj_t * ui_conectaBroker1;
extern lv_obj_t * ui_labelBotaoConecta1;
extern lv_obj_t * ui_Spinner3;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label40;
extern void ui_event_tecladoIP1(lv_event_t * e);
extern lv_obj_t * ui_tecladoIP1;
extern void ui_event_tecladoPorta1(lv_event_t * e);
extern lv_obj_t * ui_tecladoPorta1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

