// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: espDisplayUi

#ifndef UI_PARAMETROSEXPERIMENTO_H
#define UI_PARAMETROSEXPERIMENTO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ParametrosExperimento
extern void ui_ParametrosExperimento_screen_init(void);
extern void ui_ParametrosExperimento_screen_destroy(void);
extern void ui_event_ParametrosExperimento(lv_event_t * e);
extern lv_obj_t * ui_ParametrosExperimento;
extern lv_obj_t * ui_painelIputs2;
extern void ui_event_inputObserKe(lv_event_t * e);
extern lv_obj_t * ui_inputObserKe;
extern void ui_event_inputRegulaK(lv_event_t * e);
extern lv_obj_t * ui_inputRegulaK;
extern void ui_event_inputNEstados(lv_event_t * e);
extern lv_obj_t * ui_inputNEstados;
extern void ui_event_inputNEntradas(lv_event_t * e);
extern lv_obj_t * ui_inputNEntradas;
extern void ui_event_inputReferencia(lv_event_t * e);
extern lv_obj_t * ui_inputReferencia;
extern lv_obj_t * ui_tituloTelaParametrosBroker2;
extern void ui_event_enviaDados(lv_event_t * e);
extern lv_obj_t * ui_enviaDados;
extern lv_obj_t * ui_labelBotaoEnviaParametro;
extern lv_obj_t * ui_Spinner4;
extern void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label41;
extern void ui_event_tecladoObservKe(lv_event_t * e);
extern lv_obj_t * ui_tecladoObservKe;
extern void ui_event_tecladoRegulaK(lv_event_t * e);
extern lv_obj_t * ui_tecladoRegulaK;
extern void ui_event_tecladoNEstados(lv_event_t * e);
extern lv_obj_t * ui_tecladoNEstados;
extern void ui_event_tecladoNEntradas(lv_event_t * e);
extern lv_obj_t * ui_tecladoNEntradas;
extern void ui_event_tecladoReferencia(lv_event_t * e);
extern lv_obj_t * ui_tecladoReferencia;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

