// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: espDisplayUi

#include "ui.h"

lv_obj_t * ui_ParametrosEspRemoto = NULL;
lv_obj_t * ui_painelIputs = NULL;
lv_obj_t * ui_inputIP = NULL;
lv_obj_t * ui_inputPorta = NULL;
lv_obj_t * ui_modoLocalRemoto = NULL;
lv_obj_t * ui_labelLocalRemoto = NULL;
lv_obj_t * ui_localRemoto = NULL;
lv_obj_t * ui_tituloTelaParametrosBroker = NULL;
lv_obj_t * ui_conectaBroker = NULL;
lv_obj_t * ui_labelBotaoConecta = NULL;
lv_obj_t * ui_Spinner2 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Label38 = NULL;
lv_obj_t * ui_tecladoIP = NULL;
lv_obj_t * ui_tecladoPorta = NULL;
// event funtions
void ui_event_ParametrosEspRemoto(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        _ui_flag_modify(ui_tecladoIP, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_tecladoPorta, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Spinner2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_inputIP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_tecladoIP, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_inputPorta(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_tecladoPorta, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_textarea_move_cursor(ui_inputIP, UI_MOVE_CURSOR_UP);
    }
}

void ui_event_localRemoto(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ParametrosEspLocal, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ParametrosEspLocal_screen_init);
        _ui_state_modify(ui_localRemoto, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_conectaBroker(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Spinner2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_screen_change(&ui_telaAnimacao, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 8000, &ui_telaAnimacao_screen_init);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_InicialScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_InicialScreen_screen_init);
    }
}

void ui_event_tecladoIP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_tecladoIP, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_tecladoPorta(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_tecladoPorta, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

void ui_ParametrosEspRemoto_screen_init(void)
{
    ui_ParametrosEspRemoto = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ParametrosEspRemoto,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_ParametrosEspRemoto, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_ParametrosEspRemoto, LV_DIR_TOP);
    lv_obj_set_scroll_snap_x(ui_ParametrosEspRemoto, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_style_bg_color(ui_ParametrosEspRemoto, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ParametrosEspRemoto, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_painelIputs = lv_obj_create(ui_ParametrosEspRemoto);
    lv_obj_set_width(ui_painelIputs, 300);
    lv_obj_set_height(ui_painelIputs, 137);
    lv_obj_set_x(ui_painelIputs, 0);
    lv_obj_set_y(ui_painelIputs, -8);
    lv_obj_set_align(ui_painelIputs, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_painelIputs, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_painelIputs, lv_color_hex(0xE0DFFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_painelIputs, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_inputIP = lv_textarea_create(ui_painelIputs);
    lv_obj_set_width(ui_inputIP, 250);
    lv_obj_set_height(ui_inputIP, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_inputIP, -18);
    lv_obj_set_y(ui_inputIP, -41);
    lv_obj_set_align(ui_inputIP, LV_ALIGN_CENTER);
    if("123456789." == "") lv_textarea_set_accepted_chars(ui_inputIP, NULL);
    else lv_textarea_set_accepted_chars(ui_inputIP, "123456789.");
    lv_textarea_set_max_length(ui_inputIP, 15);
    lv_textarea_set_placeholder_text(ui_inputIP, "IP do Broker");
    lv_textarea_set_one_line(ui_inputIP, true);

    ui_inputPorta = lv_textarea_create(ui_painelIputs);
    lv_obj_set_width(ui_inputPorta, 181);
    lv_obj_set_height(ui_inputPorta, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_inputPorta, -50);
    lv_obj_set_y(ui_inputPorta, 6);
    lv_obj_set_align(ui_inputPorta, LV_ALIGN_CENTER);
    if("123456789" == "") lv_textarea_set_accepted_chars(ui_inputPorta, NULL);
    else lv_textarea_set_accepted_chars(ui_inputPorta, "123456789");
    lv_textarea_set_max_length(ui_inputPorta, 4);
    lv_textarea_set_placeholder_text(ui_inputPorta, "Porta do Broker");
    lv_textarea_set_one_line(ui_inputPorta, true);

    ui_modoLocalRemoto = lv_obj_create(ui_painelIputs);
    lv_obj_remove_style_all(ui_modoLocalRemoto);
    lv_obj_set_width(ui_modoLocalRemoto, 298);
    lv_obj_set_height(ui_modoLocalRemoto, 33);
    lv_obj_set_x(ui_modoLocalRemoto, 1);
    lv_obj_set_y(ui_modoLocalRemoto, 47);
    lv_obj_set_align(ui_modoLocalRemoto, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_modoLocalRemoto, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labelLocalRemoto = lv_label_create(ui_modoLocalRemoto);
    lv_obj_set_width(ui_labelLocalRemoto, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelLocalRemoto, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelLocalRemoto, -29);
    lv_obj_set_y(ui_labelLocalRemoto, -2);
    lv_obj_set_align(ui_labelLocalRemoto, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelLocalRemoto, "Experimento em modo local?");

    ui_localRemoto = lv_switch_create(ui_modoLocalRemoto);
    lv_obj_set_width(ui_localRemoto, 50);
    lv_obj_set_height(ui_localRemoto, 25);
    lv_obj_set_x(ui_localRemoto, 119);
    lv_obj_set_y(ui_localRemoto, -2);
    lv_obj_set_align(ui_localRemoto, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_localRemoto, lv_color_hex(0xABAAAD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_localRemoto, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_localRemoto, lv_color_hex(0xE0DFFD), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_localRemoto, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_localRemoto, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_localRemoto, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_localRemoto, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_localRemoto, 255, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_localRemoto, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_localRemoto, 255, LV_PART_KNOB | LV_STATE_PRESSED);

    ui_tituloTelaParametrosBroker = lv_label_create(ui_ParametrosEspRemoto);
    lv_obj_set_width(ui_tituloTelaParametrosBroker, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tituloTelaParametrosBroker, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tituloTelaParametrosBroker, -17);
    lv_obj_set_y(ui_tituloTelaParametrosBroker, -100);
    lv_obj_set_align(ui_tituloTelaParametrosBroker, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tituloTelaParametrosBroker, "Insira os dados abaixo para conectar a \nbancada ao broker");
    lv_obj_set_style_text_align(ui_tituloTelaParametrosBroker, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_conectaBroker = lv_btn_create(ui_ParametrosEspRemoto);
    lv_obj_set_width(ui_conectaBroker, 174);
    lv_obj_set_height(ui_conectaBroker, 32);
    lv_obj_set_x(ui_conectaBroker, 61);
    lv_obj_set_y(ui_conectaBroker, 90);
    lv_obj_set_align(ui_conectaBroker, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_conectaBroker, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_conectaBroker, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_conectaBroker, lv_color_hex(0x4AED56), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_conectaBroker, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_conectaBroker, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_conectaBroker, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_conectaBroker, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelBotaoConecta = lv_label_create(ui_conectaBroker);
    lv_obj_set_width(ui_labelBotaoConecta, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelBotaoConecta, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelBotaoConecta, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelBotaoConecta, "Conectar ao broker");

    ui_Spinner2 = lv_spinner_create(ui_ParametrosEspRemoto, 1000, 90);
    lv_obj_set_width(ui_Spinner2, 33);
    lv_obj_set_height(ui_Spinner2, 26);
    lv_obj_set_x(ui_Spinner2, -126);
    lv_obj_set_y(ui_Spinner2, 92);
    lv_obj_set_align(ui_Spinner2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner2, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Spinner2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Spinner2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Spinner2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Spinner2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Spinner2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Spinner2, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner2, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_ParametrosEspRemoto);
    lv_obj_set_width(ui_Button3, 25);
    lv_obj_set_height(ui_Button3, 25);
    lv_obj_set_x(ui_Button3, 141);
    lv_obj_set_y(ui_Button3, -104);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xF30606), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label38 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, "x");

    ui_tecladoIP = lv_keyboard_create(ui_ParametrosEspRemoto);
    lv_keyboard_set_mode(ui_tecladoIP, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_tecladoIP, 320);
    lv_obj_set_height(ui_tecladoIP, 120);
    lv_obj_set_x(ui_tecladoIP, 0);
    lv_obj_set_y(ui_tecladoIP, 57);
    lv_obj_set_align(ui_tecladoIP, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tecladoIP, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_tecladoPorta = lv_keyboard_create(ui_ParametrosEspRemoto);
    lv_keyboard_set_mode(ui_tecladoPorta, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_tecladoPorta, 320);
    lv_obj_set_height(ui_tecladoPorta, 120);
    lv_obj_set_x(ui_tecladoPorta, 0);
    lv_obj_set_y(ui_tecladoPorta, 57);
    lv_obj_set_align(ui_tecladoPorta, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tecladoPorta, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_inputIP, ui_event_inputIP, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_inputPorta, ui_event_inputPorta, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_localRemoto, ui_event_localRemoto, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_conectaBroker, ui_event_conectaBroker, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_tecladoIP, ui_inputIP);
    lv_obj_add_event_cb(ui_tecladoIP, ui_event_tecladoIP, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_tecladoPorta, ui_inputPorta);
    lv_obj_add_event_cb(ui_tecladoPorta, ui_event_tecladoPorta, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ParametrosEspRemoto, ui_event_ParametrosEspRemoto, LV_EVENT_ALL, NULL);

}

void ui_ParametrosEspRemoto_screen_destroy(void)
{
    if(ui_ParametrosEspRemoto) lv_obj_del(ui_ParametrosEspRemoto);

    // NULL screen variables
    ui_ParametrosEspRemoto = NULL;
    ui_painelIputs = NULL;
    ui_inputIP = NULL;
    ui_inputPorta = NULL;
    ui_modoLocalRemoto = NULL;
    ui_labelLocalRemoto = NULL;
    ui_localRemoto = NULL;
    ui_tituloTelaParametrosBroker = NULL;
    ui_conectaBroker = NULL;
    ui_labelBotaoConecta = NULL;
    ui_Spinner2 = NULL;
    ui_Button3 = NULL;
    ui_Label38 = NULL;
    ui_tecladoIP = NULL;
    ui_tecladoPorta = NULL;

}
