// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: espDisplayUi

#include "ui.h"

lv_obj_t * ui_ParametrosExperimento = NULL;
lv_obj_t * ui_painelIputs2 = NULL;
lv_obj_t * ui_inputObserKe = NULL;
lv_obj_t * ui_inputRegulaK = NULL;
lv_obj_t * ui_inputNEstados = NULL;
lv_obj_t * ui_inputNEntradas = NULL;
lv_obj_t * ui_inputReferencia = NULL;
lv_obj_t * ui_tituloTelaParametrosBroker2 = NULL;
lv_obj_t * ui_enviaDados = NULL;
lv_obj_t * ui_labelBotaoEnviaParametro = NULL;
lv_obj_t * ui_Spinner4 = NULL;
lv_obj_t * ui_Button6 = NULL;
lv_obj_t * ui_Label41 = NULL;
lv_obj_t * ui_tecladoObservKe = NULL;
lv_obj_t * ui_tecladoRegulaK = NULL;
lv_obj_t * ui_tecladoNEstados = NULL;
lv_obj_t * ui_tecladoNEntradas = NULL;
lv_obj_t * ui_tecladoReferencia = NULL;
// event funtions
void ui_event_ParametrosExperimento(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        _ui_flag_modify(ui_tecladoObservKe, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_tecladoRegulaK, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Spinner4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_inputObserKe(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_tecladoObservKe, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_inputRegulaK(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_tecladoRegulaK, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_textarea_move_cursor(ui_inputRegulaK, UI_MOVE_CURSOR_UP);
    }
}

void ui_event_inputNEstados(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_tecladoNEstados, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_textarea_move_cursor(ui_inputNEstados, UI_MOVE_CURSOR_UP);
    }
}

void ui_event_inputNEntradas(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_tecladoNEntradas, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_textarea_move_cursor(ui_inputNEntradas, UI_MOVE_CURSOR_UP);
    }
}

void ui_event_inputReferencia(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_tecladoReferencia, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_textarea_move_cursor(ui_inputReferencia, UI_MOVE_CURSOR_UP);
    }
}

void ui_event_enviaDados(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Spinner4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_screen_change(&ui_telaAnimacaoLocal, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 8000, &ui_telaAnimacaoLocal_screen_init);
    }
}

void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_InicialScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_InicialScreen_screen_init);
    }
}

void ui_event_tecladoObservKe(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_tecladoObservKe, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_tecladoRegulaK(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_tecladoRegulaK, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_tecladoNEstados(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_tecladoNEstados, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_tecladoNEntradas(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_tecladoNEntradas, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_tecladoReferencia(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_tecladoReferencia, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

void ui_ParametrosExperimento_screen_init(void)
{
    ui_ParametrosExperimento = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ParametrosExperimento,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_ParametrosExperimento, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_snap_x(ui_ParametrosExperimento, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_style_bg_color(ui_ParametrosExperimento, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ParametrosExperimento, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_painelIputs2 = lv_obj_create(ui_ParametrosExperimento);
    lv_obj_set_width(ui_painelIputs2, 300);
    lv_obj_set_height(ui_painelIputs2, 137);
    lv_obj_set_x(ui_painelIputs2, 0);
    lv_obj_set_y(ui_painelIputs2, -8);
    lv_obj_set_align(ui_painelIputs2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_painelIputs2, LV_OBJ_FLAG_SCROLL_WITH_ARROW | LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_clear_flag(ui_painelIputs2, LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scrollbar_mode(ui_painelIputs2, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_painelIputs2, LV_DIR_VER);
    lv_obj_set_scroll_snap_x(ui_painelIputs2, LV_SCROLL_SNAP_END);
    lv_obj_set_style_bg_color(ui_painelIputs2, lv_color_hex(0xE0DFFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_painelIputs2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_inputObserKe = lv_textarea_create(ui_painelIputs2);
    lv_obj_set_width(ui_inputObserKe, 176);
    lv_obj_set_height(ui_inputObserKe, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_inputObserKe, -51);
    lv_obj_set_y(ui_inputObserKe, -41);
    lv_obj_set_align(ui_inputObserKe, LV_ALIGN_CENTER);
    if("123456789," == "") lv_textarea_set_accepted_chars(ui_inputObserKe, NULL);
    else lv_textarea_set_accepted_chars(ui_inputObserKe, "123456789,");
    lv_textarea_set_max_length(ui_inputObserKe, 6);
    lv_textarea_set_placeholder_text(ui_inputObserKe, "Observador Ke");
    lv_textarea_set_one_line(ui_inputObserKe, true);

    ui_inputRegulaK = lv_textarea_create(ui_painelIputs2);
    lv_obj_set_width(ui_inputRegulaK, 181);
    lv_obj_set_height(ui_inputRegulaK, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_inputRegulaK, -50);
    lv_obj_set_y(ui_inputRegulaK, 6);
    lv_obj_set_align(ui_inputRegulaK, LV_ALIGN_CENTER);
    if("123456789," == "") lv_textarea_set_accepted_chars(ui_inputRegulaK, NULL);
    else lv_textarea_set_accepted_chars(ui_inputRegulaK, "123456789,");
    lv_textarea_set_max_length(ui_inputRegulaK, 6);
    lv_textarea_set_placeholder_text(ui_inputRegulaK, "Regulador K");
    lv_textarea_set_one_line(ui_inputRegulaK, true);

    ui_inputNEstados = lv_textarea_create(ui_painelIputs2);
    lv_obj_set_width(ui_inputNEstados, 181);
    lv_obj_set_height(ui_inputNEstados, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_inputNEstados, -50);
    lv_obj_set_y(ui_inputNEstados, 54);
    lv_obj_set_align(ui_inputNEstados, LV_ALIGN_CENTER);
    if("123456789," == "") lv_textarea_set_accepted_chars(ui_inputNEstados, NULL);
    else lv_textarea_set_accepted_chars(ui_inputNEstados, "123456789,");
    lv_textarea_set_max_length(ui_inputNEstados, 6);
    lv_textarea_set_placeholder_text(ui_inputNEstados, "N° de estados Nx");
    lv_textarea_set_one_line(ui_inputNEstados, true);

    ui_inputNEntradas = lv_textarea_create(ui_painelIputs2);
    lv_obj_set_width(ui_inputNEntradas, 181);
    lv_obj_set_height(ui_inputNEntradas, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_inputNEntradas, -51);
    lv_obj_set_y(ui_inputNEntradas, 101);
    lv_obj_set_align(ui_inputNEntradas, LV_ALIGN_CENTER);
    if("123456789," == "") lv_textarea_set_accepted_chars(ui_inputNEntradas, NULL);
    else lv_textarea_set_accepted_chars(ui_inputNEntradas, "123456789,");
    lv_textarea_set_max_length(ui_inputNEntradas, 6);
    lv_textarea_set_placeholder_text(ui_inputNEntradas, "N° de entradas Nu");
    lv_textarea_set_one_line(ui_inputNEntradas, true);

    ui_inputReferencia = lv_textarea_create(ui_painelIputs2);
    lv_obj_set_width(ui_inputReferencia, 181);
    lv_obj_set_height(ui_inputReferencia, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_inputReferencia, -47);
    lv_obj_set_y(ui_inputReferencia, 146);
    lv_obj_set_align(ui_inputReferencia, LV_ALIGN_CENTER);
    if("123456789," == "") lv_textarea_set_accepted_chars(ui_inputReferencia, NULL);
    else lv_textarea_set_accepted_chars(ui_inputReferencia, "123456789,");
    lv_textarea_set_max_length(ui_inputReferencia, 6);
    lv_textarea_set_placeholder_text(ui_inputReferencia, "Referencia");

    ui_tituloTelaParametrosBroker2 = lv_label_create(ui_ParametrosExperimento);
    lv_obj_set_width(ui_tituloTelaParametrosBroker2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tituloTelaParametrosBroker2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tituloTelaParametrosBroker2, -27);
    lv_obj_set_y(ui_tituloTelaParametrosBroker2, -99);
    lv_obj_set_align(ui_tituloTelaParametrosBroker2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tituloTelaParametrosBroker2,
                      "Insira os dados abaixo para enviar a \nbancada os dados experimentais");
    lv_obj_set_style_text_align(ui_tituloTelaParametrosBroker2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_enviaDados = lv_btn_create(ui_ParametrosExperimento);
    lv_obj_set_width(ui_enviaDados, 174);
    lv_obj_set_height(ui_enviaDados, 32);
    lv_obj_set_x(ui_enviaDados, 61);
    lv_obj_set_y(ui_enviaDados, 90);
    lv_obj_set_align(ui_enviaDados, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_enviaDados, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_enviaDados, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_enviaDados, lv_color_hex(0x4AED56), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_enviaDados, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_enviaDados, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_enviaDados, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_enviaDados, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelBotaoEnviaParametro = lv_label_create(ui_enviaDados);
    lv_obj_set_width(ui_labelBotaoEnviaParametro, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelBotaoEnviaParametro, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelBotaoEnviaParametro, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelBotaoEnviaParametro, "Enviar dados");

    ui_Spinner4 = lv_spinner_create(ui_ParametrosExperimento, 1000, 90);
    lv_obj_set_width(ui_Spinner4, 33);
    lv_obj_set_height(ui_Spinner4, 26);
    lv_obj_set_x(ui_Spinner4, -126);
    lv_obj_set_y(ui_Spinner4, 92);
    lv_obj_set_align(ui_Spinner4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner4, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Spinner4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Spinner4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Spinner4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Spinner4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Spinner4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Spinner4, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner4, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Button6 = lv_btn_create(ui_ParametrosExperimento);
    lv_obj_set_width(ui_Button6, 25);
    lv_obj_set_height(ui_Button6, 25);
    lv_obj_set_x(ui_Button6, 145);
    lv_obj_set_y(ui_Button6, -106);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0xF60202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label41 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "x");

    ui_tecladoObservKe = lv_keyboard_create(ui_ParametrosExperimento);
    lv_keyboard_set_mode(ui_tecladoObservKe, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_tecladoObservKe, 320);
    lv_obj_set_height(ui_tecladoObservKe, 120);
    lv_obj_set_x(ui_tecladoObservKe, 0);
    lv_obj_set_y(ui_tecladoObservKe, 57);
    lv_obj_set_align(ui_tecladoObservKe, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tecladoObservKe, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_tecladoRegulaK = lv_keyboard_create(ui_ParametrosExperimento);
    lv_keyboard_set_mode(ui_tecladoRegulaK, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_tecladoRegulaK, 320);
    lv_obj_set_height(ui_tecladoRegulaK, 120);
    lv_obj_set_x(ui_tecladoRegulaK, 0);
    lv_obj_set_y(ui_tecladoRegulaK, 57);
    lv_obj_set_align(ui_tecladoRegulaK, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tecladoRegulaK, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_tecladoNEstados = lv_keyboard_create(ui_ParametrosExperimento);
    lv_keyboard_set_mode(ui_tecladoNEstados, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_tecladoNEstados, 320);
    lv_obj_set_height(ui_tecladoNEstados, 120);
    lv_obj_set_x(ui_tecladoNEstados, 0);
    lv_obj_set_y(ui_tecladoNEstados, 57);
    lv_obj_set_align(ui_tecladoNEstados, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tecladoNEstados, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_tecladoNEntradas = lv_keyboard_create(ui_ParametrosExperimento);
    lv_keyboard_set_mode(ui_tecladoNEntradas, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_tecladoNEntradas, 320);
    lv_obj_set_height(ui_tecladoNEntradas, 120);
    lv_obj_set_x(ui_tecladoNEntradas, 0);
    lv_obj_set_y(ui_tecladoNEntradas, 57);
    lv_obj_set_align(ui_tecladoNEntradas, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tecladoNEntradas, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_tecladoReferencia = lv_keyboard_create(ui_ParametrosExperimento);
    lv_keyboard_set_mode(ui_tecladoReferencia, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_tecladoReferencia, 320);
    lv_obj_set_height(ui_tecladoReferencia, 120);
    lv_obj_set_x(ui_tecladoReferencia, 0);
    lv_obj_set_y(ui_tecladoReferencia, 57);
    lv_obj_set_align(ui_tecladoReferencia, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tecladoReferencia, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_inputObserKe, ui_event_inputObserKe, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_inputRegulaK, ui_event_inputRegulaK, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_inputNEstados, ui_event_inputNEstados, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_inputNEntradas, ui_event_inputNEntradas, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_inputReferencia, ui_event_inputReferencia, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_enviaDados, ui_event_enviaDados, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_tecladoObservKe, ui_inputObserKe);
    lv_obj_add_event_cb(ui_tecladoObservKe, ui_event_tecladoObservKe, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_tecladoRegulaK, ui_inputRegulaK);
    lv_obj_add_event_cb(ui_tecladoRegulaK, ui_event_tecladoRegulaK, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_tecladoNEstados, ui_inputNEstados);
    lv_obj_add_event_cb(ui_tecladoNEstados, ui_event_tecladoNEstados, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_tecladoNEntradas, ui_inputNEntradas);
    lv_obj_add_event_cb(ui_tecladoNEntradas, ui_event_tecladoNEntradas, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_tecladoReferencia, ui_inputReferencia);
    lv_obj_add_event_cb(ui_tecladoReferencia, ui_event_tecladoReferencia, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ParametrosExperimento, ui_event_ParametrosExperimento, LV_EVENT_ALL, NULL);

}

void ui_ParametrosExperimento_screen_destroy(void)
{
    if(ui_ParametrosExperimento) lv_obj_del(ui_ParametrosExperimento);

    // NULL screen variables
    ui_ParametrosExperimento = NULL;
    ui_painelIputs2 = NULL;
    ui_inputObserKe = NULL;
    ui_inputRegulaK = NULL;
    ui_inputNEstados = NULL;
    ui_inputNEntradas = NULL;
    ui_inputReferencia = NULL;
    ui_tituloTelaParametrosBroker2 = NULL;
    ui_enviaDados = NULL;
    ui_labelBotaoEnviaParametro = NULL;
    ui_Spinner4 = NULL;
    ui_Button6 = NULL;
    ui_Label41 = NULL;
    ui_tecladoObservKe = NULL;
    ui_tecladoRegulaK = NULL;
    ui_tecladoNEstados = NULL;
    ui_tecladoNEntradas = NULL;
    ui_tecladoReferencia = NULL;

}
