// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: espDisplayUi

#ifndef UI_TELAANIMACAO_H
#define UI_TELAANIMACAO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_telaAnimacao
extern void ui_telaAnimacao_screen_init(void);
extern void ui_telaAnimacao_screen_destroy(void);
extern lv_obj_t * ui_telaAnimacao;
extern lv_obj_t * ui_barnivelagua;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_labelValorNvel;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label19;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label39;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

