// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: espDisplayUi

#ifndef UI_TELAANIMACAOLOCAL_H
#define UI_TELAANIMACAOLOCAL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_telaAnimacaoLocal
extern void ui_telaAnimacaoLocal_screen_init(void);
extern void ui_telaAnimacaoLocal_screen_destroy(void);
extern void ui_event_telaAnimacaoLocal(lv_event_t * e);
extern lv_obj_t * ui_telaAnimacaoLocal;
extern lv_obj_t * ui_barnivelagua1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_labelValorNvel1;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_Label36;
extern void ui_event_atualizaReferencia(lv_event_t * e);
extern lv_obj_t * ui_atualizaReferencia;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_Spinner5;
extern void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label42;
extern void ui_event_Keyboard5(lv_event_t * e);
extern lv_obj_t * ui_Keyboard5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

