// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: espDisplayUi

#include "ui.h"

lv_obj_t * ui_telaAnimacao = NULL;
lv_obj_t * ui_barnivelagua = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_labelValorNvel = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Label39 = NULL;
// event funtions
void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_InicialScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_InicialScreen_screen_init);
    }
}

// build funtions

void ui_telaAnimacao_screen_init(void)
{
    ui_telaAnimacao = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_telaAnimacao, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_barnivelagua = lv_bar_create(ui_telaAnimacao);
    lv_bar_set_range(ui_barnivelagua, 0, 17);
    lv_bar_set_value(ui_barnivelagua, 16, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_barnivelagua, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_barnivelagua, 190);
    lv_obj_set_height(ui_barnivelagua, 72);
    lv_obj_set_x(ui_barnivelagua, -3);
    lv_obj_set_y(ui_barnivelagua, 127);
    lv_obj_set_align(ui_barnivelagua, LV_ALIGN_CENTER);
    lv_obj_set_style_transform_angle(ui_barnivelagua, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_telaAnimacao);
    lv_obj_set_width(ui_Panel4, 150);
    lv_obj_set_height(ui_Panel4, 50);
    lv_obj_set_x(ui_Panel4, 79);
    lv_obj_set_y(ui_Panel4, -69);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xCCC7C7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 5);
    lv_obj_set_y(ui_Label6, 0);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Nivel da agua");

    ui_Panel5 = lv_obj_create(ui_telaAnimacao);
    lv_obj_set_width(ui_Panel5, 150);
    lv_obj_set_height(ui_Panel5, 50);
    lv_obj_set_x(ui_Panel5, 76);
    lv_obj_set_y(ui_Panel5, -17);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labelValorNvel = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_labelValorNvel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelValorNvel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelValorNvel, 0);
    lv_obj_set_y(ui_labelValorNvel, 1);
    lv_obj_set_align(ui_labelValorNvel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelValorNvel, "0");

    ui_Label8 = lv_label_create(ui_telaAnimacao);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -48);
    lv_obj_set_y(ui_Label8, 79);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "-----");

    ui_Label1 = lv_label_create(ui_telaAnimacao);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -41);
    lv_obj_set_y(ui_Label1, 68);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "-----");

    ui_Label2 = lv_label_create(ui_telaAnimacao);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -41);
    lv_obj_set_y(ui_Label2, 58);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "-----");

    ui_Label5 = lv_label_create(ui_telaAnimacao);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -41);
    lv_obj_set_y(ui_Label5, 47);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "-----");

    ui_Label7 = lv_label_create(ui_telaAnimacao);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -41);
    lv_obj_set_y(ui_Label7, 36);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "-----");

    ui_Label9 = lv_label_create(ui_telaAnimacao);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -41);
    lv_obj_set_y(ui_Label9, 24);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "-----");

    ui_Label10 = lv_label_create(ui_telaAnimacao);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -40);
    lv_obj_set_y(ui_Label10, 13);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "-----");

    ui_Label11 = lv_label_create(ui_telaAnimacao);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -41);
    lv_obj_set_y(ui_Label11, 2);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "-----");

    ui_Label12 = lv_label_create(ui_telaAnimacao);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -41);
    lv_obj_set_y(ui_Label12, -9);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "-----");

    ui_Label13 = lv_label_create(ui_telaAnimacao);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -41);
    lv_obj_set_y(ui_Label13, -20);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "-----");

    ui_Label14 = lv_label_create(ui_telaAnimacao);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -41);
    lv_obj_set_y(ui_Label14, -31);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "-----");

    ui_Label15 = lv_label_create(ui_telaAnimacao);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -41);
    lv_obj_set_y(ui_Label15, -43);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "-----");

    ui_Label16 = lv_label_create(ui_telaAnimacao);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -41);
    lv_obj_set_y(ui_Label16, -55);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "-----");

    ui_Label17 = lv_label_create(ui_telaAnimacao);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -41);
    lv_obj_set_y(ui_Label17, -66);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "-----");

    ui_Label18 = lv_label_create(ui_telaAnimacao);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -41);
    lv_obj_set_y(ui_Label18, -77);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "-----");

    ui_Label19 = lv_label_create(ui_telaAnimacao);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, -49);
    lv_obj_set_y(ui_Label19, -88);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "-----");

    ui_Button4 = lv_btn_create(ui_telaAnimacao);
    lv_obj_set_width(ui_Button4, 25);
    lv_obj_set_height(ui_Button4, 25);
    lv_obj_set_x(ui_Button4, 146);
    lv_obj_set_y(ui_Button4, -108);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xFF0101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label39 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "x");

    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);

}

void ui_telaAnimacao_screen_destroy(void)
{
    if(ui_telaAnimacao) lv_obj_del(ui_telaAnimacao);

    // NULL screen variables
    ui_telaAnimacao = NULL;
    ui_barnivelagua = NULL;
    ui_Panel4 = NULL;
    ui_Label6 = NULL;
    ui_Panel5 = NULL;
    ui_labelValorNvel = NULL;
    ui_Label8 = NULL;
    ui_Label1 = NULL;
    ui_Label2 = NULL;
    ui_Label5 = NULL;
    ui_Label7 = NULL;
    ui_Label9 = NULL;
    ui_Label10 = NULL;
    ui_Label11 = NULL;
    ui_Label12 = NULL;
    ui_Label13 = NULL;
    ui_Label14 = NULL;
    ui_Label15 = NULL;
    ui_Label16 = NULL;
    ui_Label17 = NULL;
    ui_Label18 = NULL;
    ui_Label19 = NULL;
    ui_Button4 = NULL;
    ui_Label39 = NULL;

}
